import { ToolDefinition } from '../core/ToolRegistryManager';

export const MARKETPLACE_TOOLS: ToolDefinition[] = [
    {
        name: 'findTalents',
        description: 'Search for talents/profiles in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findTalents',
            description: 'Find talents',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    skills: { type: 'array', items: { type: 'string' }, description: 'Filter by skills' },
                    location: { type: 'string', description: 'Filter by location' },
                    availability: { type: 'string', enum: ['AVAILABLE', 'BUSY', 'UNAVAILABLE'], description: 'Filter by availability' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'findTools',
        description: 'Search for tools in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findTools',
            description: 'Find tools',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    category: { type: 'string', description: 'Filter by category' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    pricing: { type: 'string', enum: ['FREE', 'PAID', 'FREEMIUM'], description: 'Filter by pricing' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'findMaterials',
        description: 'Search for materials/documents in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findMaterials',
            description: 'Find materials',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    type: { type: 'string', enum: ['DOCUMENT', 'TEMPLATE', 'GUIDE', 'TUTORIAL'], description: 'Filter by material type' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'findResources',
        description: 'Search for various resources in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findResources',
            description: 'Find resources',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    resourceType: { type: 'string', description: 'Filter by resource type' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'findProjects',
        description: 'Search for published projects in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findProjects',
            description: 'Find projects',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    status: { type: 'string', enum: ['ACTIVE', 'COMPLETED'], description: 'Filter by status' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'findTeams',
        description: 'Search for published teams in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findTeams',
            description: 'Find teams',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'findTasks',
        description: 'Search for published tasks in the marketplace',
        category: 'SEARCH',
        isDefault: false,
        functionSchema: {
            name: 'findTasks',
            description: 'Find tasks',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    status: { type: 'string', enum: ['OPEN', 'IN_PROGRESS', 'COMPLETED'], description: 'Filter by status' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Filter by tags' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
];
