import { ToolDefinition } from '../core/ToolRegistryManager';

export const PROJECT_MANAGEMENT_TOOLS: ToolDefinition[] = [
    {
        name: 'createProject',
        description: 'Create a new project in the workspace',
        category: 'PROJECT_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'createProject',
            description: 'Create a project',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    name: { type: 'string', description: 'Project name (max 200 characters)' },
                    description: { type: 'string', description: 'Project description (max 5000 characters)' },
                    spaceId: { type: 'string', description: 'Space ID to associate with' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'Visibility level (default: PRIVATE)' },
                    isPublic: { type: 'boolean', description: 'Whether project is public (default: false)' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Array of tag strings' },
                    metadata: { type: 'object', description: 'Additional metadata' },
                },
                required: ['workspaceId', 'name'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 20,
        examples: [],
    },
    {
        name: 'updateProject',
        description: 'Update an existing project\'s properties',
        category: 'PROJECT_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'updateProject',
            description: 'Update a project',
            parameters: {
                type: 'object',
                properties: {
                    projectId: { type: 'string', description: 'Project ID' },
                    name: { type: 'string', description: 'New name' },
                    description: { type: 'string', description: 'New description' },
                    status: { type: 'string', enum: ['ACTIVE', 'ARCHIVED', 'COMPLETED'], description: 'New status' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'New visibility level' },
                    isPublic: { type: 'boolean', description: 'New public status' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Updated tags' },
                    metadata: { type: 'object', description: 'Updated metadata' },
                },
                required: ['projectId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 20,
        examples: [],
    },
    {
        name: 'postProjectActivities',
        description: 'Post activity updates to a project\'s activity feed',
        category: 'PROJECT_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'postProjectActivities',
            description: 'Post project activities',
            parameters: {
                type: 'object',
                properties: {
                    projectId: { type: 'string', description: 'Project ID' },
                    type: { type: 'string', enum: ['UPDATE', 'MILESTONE', 'NOTE', 'STATUS_CHANGE'], description: 'Activity type' },
                    content: { type: 'string', description: 'Activity content (max 5000 characters)' },
                    metadata: { type: 'object', description: 'Additional activity metadata' },
                    isPublic: { type: 'boolean', description: 'Whether activity is public (default: false)' },
                },
                required: ['projectId', 'type', 'content'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'reportProjectKPIs',
        description: 'Generate and retrieve KPI reports for a project',
        category: 'PROJECT_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'reportProjectKPIs',
            description: 'Report project KPIs',
            parameters: {
                type: 'object',
                properties: {
                    projectId: { type: 'string', description: 'Project ID' },
                    metrics: {
                        type: 'array',
                        items: { type: 'string', enum: ['TASK_COMPLETION', 'TEAM_VELOCITY', 'BURNDOWN', 'CYCLE_TIME', 'LEAD_TIME'] },
                        description: 'Specific metrics to include',
                    },
                    startDate: { type: 'string', description: 'Start date for report (ISO8601)' },
                    endDate: { type: 'string', description: 'End date for report (ISO8601)' },
                    format: { type: 'string', enum: ['JSON', 'CSV', 'PDF'], description: 'Report format (default: JSON)' },
                },
                required: ['projectId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 60,
        rateLimit: 10,
        examples: [],
    },
    {
        name: 'publishProjectToMarketplace',
        isDefault: false,
        description: 'Publish a project to the marketplace for discovery by other users',
        category: 'PROJECT_MANAGEMENT',
        functionSchema: {
            name: 'publishProjectToMarketplace',
            description: 'Publish project to marketplace',
            parameters: {
                type: 'object',
                properties: {
                    projectId: { type: 'string', description: 'Project ID to publish' },
                    marketplaceVisibility: { type: 'string', enum: ['PUBLIC', 'LIMITED'], description: 'Marketplace visibility (default: PUBLIC)' },
                    pricing: {
                        type: 'object',
                        description: 'Pricing information',
                        properties: {
                            type: { type: 'string', enum: ['FREE', 'PAID', 'CUSTOM'] },
                            amount: { type: 'number' },
                        },
                    },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Marketplace tags for discovery' },
                },
                required: ['projectId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 5,
        examples: [],
    },
];
