import { ToolDefinition } from '../core/ToolRegistryManager';

export const PROPOSAL_MANAGEMENT_TOOLS: ToolDefinition[] = [
    {
        name: 'createProposal',
        description: 'Create a new proposal for marketplace or workspace',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'createProposal',
            description: 'Create a proposal',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    title: { type: 'string', description: 'Proposal title (max 200 characters)' },
                    shortSummary: { type: 'string', description: 'Short summary (max 500 characters)' },
                    detailedDesc: { type: 'string', description: 'Detailed description (max 10000 characters)' },
                    category: { type: 'string', enum: ['COFOUNDER', 'MENTOR', 'CUSTOMER', 'INVESTOR', 'PARTNER', 'MEMBERSHIP'], description: 'Category' },
                    intent: { type: 'string', enum: ['SEEKING', 'OFFERING'], description: 'Intent' },
                    projectId: { type: 'string', description: 'Associated project ID' },
                    teamId: { type: 'string', description: 'Associated team ID' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'Visibility level (default: PUBLIC)' },
                    status: { type: 'string', enum: ['DRAFT', 'PUBLISHED'], description: 'Initial status (default: DRAFT)' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Array of tag strings' },
                    keywords: { type: 'array', items: { type: 'string' }, description: 'Array of keywords for search' },
                },
                required: ['title', 'shortSummary', 'detailedDesc', 'category', 'intent'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 20,
        examples: [],
    },
    {
        name: 'updateProposal',
        description: 'Update an existing proposal\'s properties',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'updateProposal',
            description: 'Update a proposal',
            parameters: {
                type: 'object',
                properties: {
                    proposalId: { type: 'string', description: 'Proposal ID' },
                    title: { type: 'string', description: 'Updated title' },
                    shortSummary: { type: 'string', description: 'Updated short summary' },
                    detailedDesc: { type: 'string', description: 'Updated detailed description' },
                    status: { type: 'string', enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], description: 'Updated status' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'Updated visibility level' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Updated tags' },
                    keywords: { type: 'array', items: { type: 'string' }, description: 'Updated keywords' },
                },
                required: ['proposalId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 20,
        examples: [],
    },
    {
        name: 'publishProposalToMarketplace',
        description: 'Publish a proposal to the marketplace (if not already published)',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'publishProposalToMarketplace',
            description: 'Publish proposal to marketplace',
            parameters: {
                type: 'object',
                properties: {
                    proposalId: { type: 'string', description: 'Proposal ID to publish' },
                    marketplaceVisibility: { type: 'string', enum: ['PUBLIC', 'LIMITED'], description: 'Marketplace visibility (default: PUBLIC)' },
                },
                required: ['proposalId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 5,
        examples: [],
    },
];
