import { ToolDefinition } from '../core/ToolRegistryManager';

export const SEARCH_TOOLS: ToolDefinition[] = [
    {
        name: 'searchWorkspaces',
        description: 'Search for workspaces by name, description, or other criteria',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchWorkspaces',
            description: 'Search workspaces',
            parameters: {
                type: 'object',
                properties: {
                    query: { type: 'string', description: 'Search query' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    includePublic: { type: 'boolean', description: 'Include public workspaces (default: true)' },
                    includePrivate: { type: 'boolean', description: 'Include private workspaces user has access to (default: true)' },
                },
                required: ['query'],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'searchProjects',
        description: 'Search for projects within workspace or across all accessible workspaces',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchProjects',
            description: 'Search projects',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Limit search to specific workspace' },
                    query: { type: 'string', description: 'Search query' },
                    status: { type: 'string', enum: ['ACTIVE', 'ARCHIVED', 'COMPLETED'], description: 'Filter by status' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                    includeArchived: { type: 'boolean', description: 'Include archived projects (default: false)' },
                },
                required: ['query'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'searchTeams',
        description: 'Search for teams within workspace or across accessible workspaces',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchTeams',
            description: 'Search teams',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Limit search to specific workspace' },
                    query: { type: 'string', description: 'Search query' },
                    status: { type: 'string', enum: ['ACTIVE', 'ARCHIVED'], description: 'Filter by status' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                },
                required: ['query'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'searchProposals',
        description: 'Search for proposals in marketplace or within workspace',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchProposals',
            description: 'Search proposals',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Limit search to workspace proposals' },
                    query: { type: 'string', description: 'Search query' },
                    category: { type: 'string', enum: ['COFOUNDER', 'MENTOR', 'CUSTOMER', 'INVESTOR', 'PARTNER', 'MEMBERSHIP'], description: 'Filter by category' },
                    status: { type: 'string', enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], description: 'Filter by status' },
                    intent: { type: 'string', enum: ['SEEKING', 'OFFERING'], description: 'Filter by intent' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                },
                required: ['query'],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'searchSpaces',
        description: 'Search for spaces within a workspace',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchSpaces',
            description: 'Search spaces',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    query: { type: 'string', description: 'Search query' },
                    limit: { type: 'number', description: 'Maximum results (default: 20, max: 100)' },
                },
                required: ['workspaceId', 'query'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'searchWorkspace',
        description: 'Search for a specific workspace by ID or unique identifier',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchWorkspace',
            description: 'Search workspace',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID to retrieve' },
                    includeDetails: { type: 'boolean', description: 'Include detailed information (default: true)' },
                },
                required: ['workspaceId'],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
    {
        name: 'searchProject',
        description: 'Search for a specific project by ID',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchProject',
            description: 'Search project',
            parameters: {
                type: 'object',
                properties: {
                    projectId: { type: 'string', description: 'Project ID to retrieve' },
                    includeDetails: { type: 'boolean', description: 'Include detailed information (default: true)' },
                },
                required: ['projectId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
    {
        name: 'searchTeam',
        description: 'Search for a specific team by ID',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchTeam',
            description: 'Search team',
            parameters: {
                type: 'object',
                properties: {
                    teamId: { type: 'string', description: 'Team ID to retrieve' },
                    includeDetails: { type: 'boolean', description: 'Include detailed information (default: true)' },
                },
                required: ['teamId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
    {
        name: 'searchProposal',
        description: 'Search for a specific proposal by ID',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchProposal',
            description: 'Search proposal',
            parameters: {
                type: 'object',
                properties: {
                    proposalId: { type: 'string', description: 'Proposal ID to retrieve' },
                    includeDetails: { type: 'boolean', description: 'Include detailed information (default: true)' },
                },
                required: ['proposalId'],
            },
        },
        deterministic: true,
        requiresAuth: false,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
    {
        name: 'searchSpace',
        description: 'Search for a specific space by ID',
        category: 'SEARCH',
        isDefault: true,
        functionSchema: {
            name: 'searchSpace',
            description: 'Search space',
            parameters: {
                type: 'object',
                properties: {
                    spaceId: { type: 'string', description: 'Space ID to retrieve' },
                    includeDetails: { type: 'boolean', description: 'Include detailed information (default: true)' },
                },
                required: ['spaceId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
];
