import { ToolDefinition } from '../core/ToolRegistryManager';

// Includes DEFAULT_TOOLS and TASK_MANAGEMENT_TOOLS from original toolRegistry.ts
export const TASK_MANAGEMENT_TOOLS: ToolDefinition[] = [
    {
        name: 'createSchedule',
        description: 'Create a scheduled task or automation that runs at specified intervals or times',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'createSchedule',
            description: 'Create a scheduled task or automation',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID where schedule will be created' },
                    name: { type: 'string', description: 'Name of the schedule' },
                    description: { type: 'string', description: 'Description of what the schedule does' },
                    cronExpression: { type: 'string', description: 'Cron expression defining schedule (e.g., "0 9 * * *" for daily at 9 AM)' },
                    timezone: { type: 'string', description: 'Timezone for schedule (default: UTC)' },
                    enabled: { type: 'boolean', description: 'Whether schedule is enabled (default: true)' },
                    action: {
                        type: 'object',
                        description: 'Action to execute when schedule triggers',
                        properties: {
                            type: { type: 'string', description: 'Action type (e.g., "CREATE_TASK", "SEND_NOTIFICATION")' },
                            parameters: { type: 'object', description: 'Action-specific parameters' },
                        },
                    },
                },
                required: ['workspaceId', 'name', 'cronExpression', 'action'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 10,
        examples: [],
    },
    {
        name: 'loadAssetsAndObjects',
        description: 'Load assets, files, and objects from workspace storage or external sources',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'loadAssetsAndObjects',
            description: 'Load assets and objects',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    assetType: { type: 'string', enum: ['FILE', 'IMAGE', 'DOCUMENT', 'VIDEO', 'AUDIO'], description: 'Type of asset to load' },
                    source: { type: 'string', enum: ['WORKSPACE', 'EXTERNAL_URL', 'CLOUD_STORAGE'], description: 'Source location' },
                    path: { type: 'string', description: 'Path within workspace (for WORKSPACE source)' },
                    url: { type: 'string', description: 'External URL (for EXTERNAL_URL source)' },
                    storageProvider: { type: 'string', description: 'Cloud storage provider (for CLOUD_STORAGE source)' },
                    includeMetadata: { type: 'boolean', description: 'Include file metadata (default: true)' },
                    limit: { type: 'number', description: 'Maximum number of assets to load (default: 100)' },
                },
                required: ['workspaceId', 'assetType', 'source'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'retrieveChatMessages',
        description: 'Retrieve chat messages from workspace channels, direct messages, or agent conversations',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'retrieveChatMessages',
            description: 'Retrieve chat messages',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    channelId: { type: 'string', description: 'Channel ID (for channel messages)' },
                    conversationId: { type: 'string', description: 'Conversation ID (for direct messages)' },
                    agentId: { type: 'string', description: 'Agent ID (for agent conversations)' },
                    userId: { type: 'string', description: 'User ID (for user-specific messages)' },
                    limit: { type: 'number', description: 'Maximum number of messages (default: 50, max: 200)' },
                    before: { type: 'string', description: 'Message ID to fetch messages before (pagination)' },
                    after: { type: 'string', description: 'Message ID to fetch messages after (pagination)' },
                    includeAttachments: { type: 'boolean', description: 'Include message attachments (default: false)' },
                },
                required: ['workspaceId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
    {
        name: 'postReply',
        description: 'Post a reply to a chat message, comment, or conversation thread',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'postReply',
            description: 'Post a reply',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    messageId: { type: 'string', description: 'ID of message to reply to' },
                    content: { type: 'string', description: 'Reply content (max 10000 characters)' },
                    channelId: { type: 'string', description: 'Channel ID (if replying in channel)' },
                    conversationId: { type: 'string', description: 'Conversation ID (if replying in DM)' },
                    mentions: { type: 'array', items: { type: 'string' }, description: 'Array of user IDs to mention' },
                    attachments: { type: 'array', items: { type: 'string' }, description: 'Array of attachment IDs' },
                    isPrivate: { type: 'boolean', description: 'Whether reply is private (default: false)' },
                },
                required: ['workspaceId', 'messageId', 'content'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'retrieveTaskList',
        description: 'Retrieve a list of tasks with optional filtering and pagination',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'retrieveTaskList',
            description: 'Retrieve task list',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID filter' },
                    spaceId: { type: 'string', description: 'Space ID filter' },
                    projectId: { type: 'string', description: 'Project ID filter' },
                    teamId: { type: 'string', description: 'Team ID filter' },
                    listId: { type: 'string', description: 'List ID filter' },
                    assigneeId: { type: 'string', description: 'Assignee user ID filter' },
                    status: { type: 'array', items: { type: 'string' }, description: 'Array of status values to filter by' },
                    query: { type: 'string', description: 'Search query for task title/description' },
                    page: { type: 'number', description: 'Page number (default: 1)' },
                    pageSize: { type: 'number', description: 'Items per page (default: 12, max: 50)' },
                    scope: { type: 'string', enum: ['owned', 'assigned', 'all'], description: 'Scope filter (default: owned)' },
                    includeRelations: { type: 'boolean', description: 'Include related data (default: false)' },
                },
                required: [],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 60,
        examples: [],
    },
    {
        name: 'addTaskToList',
        description: 'Add an existing task to one or more lists',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'addTaskToList',
            description: 'Add task to lists',
            parameters: {
                type: 'object',
                properties: {
                    taskId: { type: 'string', description: 'Task ID to add to lists' },
                    listIds: { type: 'array', items: { type: 'string' }, description: 'Array of list IDs to add task to' },
                    workspaceId: { type: 'string', description: 'Workspace ID for validation' },
                },
                required: ['taskId', 'listIds'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'createTask',
        description: 'Create a new task in the workspace',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'createTask',
            description: 'Create a new task',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    spaceId: { type: 'string', description: 'Space ID' },
                    projectId: { type: 'string', description: 'Project ID' },
                    teamId: { type: 'string', description: 'Team ID' },
                    listId: { type: 'string', description: 'List ID' },
                    title: { type: 'string', description: 'Task title (max 500 characters)' },
                    description: { type: 'string', description: 'Task description (max 10000 characters)' },
                    assigneeIds: { type: 'array', items: { type: 'string' }, description: 'Array of user IDs to assign' },
                    agentIds: { type: 'array', items: { type: 'string' }, description: 'Array of agent IDs to assign' },
                    status: { type: 'string', description: 'Initial status' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'Visibility level (default: PRIVATE)' },
                    isPublic: { type: 'boolean', description: 'Whether task is public (default: false)' },
                    parentId: { type: 'string', description: 'Parent task ID (for subtasks)' },
                },
                required: ['title'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'createSubtask',
        description: 'Create a subtask under a parent task',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'createSubtask',
            description: 'Create a subtask',
            parameters: {
                type: 'object',
                properties: {
                    parentId: { type: 'string', description: 'Parent task ID' },
                    title: { type: 'string', description: 'Subtask title (max 500 characters)' },
                    description: { type: 'string', description: 'Subtask description' },
                    assigneeIds: { type: 'array', items: { type: 'string' }, description: 'Array of user IDs to assign' },
                    agentIds: { type: 'array', items: { type: 'string' }, description: 'Array of agent IDs to assign' },
                    status: { type: 'string', description: 'Initial status' },
                },
                required: ['parentId', 'title'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'moveToList',
        description: 'Move a task from one list to another',
        category: 'TASK_MANAGEMENT',
        isDefault: true,
        functionSchema: {
            name: 'moveToList',
            description: 'Move task to list',
            parameters: {
                type: 'object',
                properties: {
                    taskId: { type: 'string', description: 'Task ID to move' },
                    targetListId: { type: 'string', description: 'Target list ID' },
                    removeFromCurrentList: { type: 'boolean', description: 'Remove from current list (default: true)' },
                    preserveStatus: { type: 'boolean', description: 'Preserve task status (default: false)' },
                },
                required: ['taskId', 'targetListId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'postTaskComment',
        description: 'Post a comment on a task',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'postTaskComment',
            description: 'Post task comment',
            parameters: {
                type: 'object',
                properties: {
                    taskId: { type: 'string', description: 'Task ID' },
                    content: { type: 'string', description: 'Comment content (max 10000 characters)' },
                    mentions: { type: 'array', items: { type: 'string' }, description: 'Array of user IDs to mention' },
                    isPrivate: { type: 'boolean', description: 'Whether comment is private (default: false)' },
                    attachments: { type: 'array', items: { type: 'string' }, description: 'Array of attachment IDs' },
                },
                required: ['taskId', 'content'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'updateTaskComment',
        description: 'Update an existing task comment',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'updateTaskComment',
            description: 'Update task comment',
            parameters: {
                type: 'object',
                properties: {
                    commentId: { type: 'string', description: 'Comment ID' },
                    content: { type: 'string', description: 'Updated comment content (max 10000 characters)' },
                    mentions: { type: 'array', items: { type: 'string' }, description: 'Updated array of user IDs to mention' },
                },
                required: ['commentId', 'content'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'updateTask',
        description: 'Update an existing task\'s properties',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'updateTask',
            description: 'Update a task',
            parameters: {
                type: 'object',
                properties: {
                    taskId: { type: 'string', description: 'Task ID' },
                    title: { type: 'string', description: 'New title' },
                    description: { type: 'string', description: 'New description' },
                    status: { type: 'string', description: 'New status' },
                    assigneeIds: { type: 'array', items: { type: 'string' }, description: 'New array of user assignee IDs' },
                    agentIds: { type: 'array', items: { type: 'string' }, description: 'New array of agent assignee IDs' },
                    projectId: { type: 'string', description: 'New project ID' },
                    teamId: { type: 'string', description: 'New team ID' },
                    listId: { type: 'string', description: 'New list ID' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'New visibility level' },
                    isPublic: { type: 'boolean', description: 'New public status' },
                    parentId: { type: 'string', description: 'New parent task ID' },
                },
                required: ['taskId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
];
