import { ToolDefinition } from '../core/ToolRegistryManager';

export const TEAM_MANAGEMENT_TOOLS: ToolDefinition[] = [
    {
        name: 'createTeam',
        description: 'Create a new team in the workspace',
        category: 'TASK_MANAGEMENT', // Kept as original category from toolRegistry
        isDefault: true,
        functionSchema: {
            name: 'createTeam',
            description: 'Create a team',
            parameters: {
                type: 'object',
                properties: {
                    workspaceId: { type: 'string', description: 'Workspace ID' },
                    name: { type: 'string', description: 'Team name (max 200 characters)' },
                    description: { type: 'string', description: 'Team description (max 5000 characters)' },
                    spaceId: { type: 'string', description: 'Space ID to associate with' },
                    memberIds: { type: 'array', items: { type: 'string' }, description: 'Initial member user IDs' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'Visibility level (default: PRIVATE)' },
                    isPublic: { type: 'boolean', description: 'Whether team is public (default: false)' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Array of tag strings' },
                },
                required: ['workspaceId', 'name'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 20,
        examples: [],
    },
    {
        name: 'updateTeam',
        description: 'Update an existing team\'s properties',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'updateTeam',
            description: 'Update a team',
            parameters: {
                type: 'object',
                properties: {
                    teamId: { type: 'string', description: 'Team ID' },
                    name: { type: 'string', description: 'New name' },
                    description: { type: 'string', description: 'New description' },
                    status: { type: 'string', enum: ['ACTIVE', 'ARCHIVED'], description: 'New status' },
                    visibility: { type: 'string', enum: ['PRIVATE', 'TEAM', 'WORKSPACE', 'PUBLIC'], description: 'New visibility level' },
                    isPublic: { type: 'boolean', description: 'New public status' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Updated tags' },
                    addMemberIds: { type: 'array', items: { type: 'string' }, description: 'User IDs to add to team' },
                    removeMemberIds: { type: 'array', items: { type: 'string' }, description: 'User IDs to remove from team' },
                },
                required: ['teamId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 20,
        examples: [],
    },
    {
        name: 'postTeamActivities',
        description: 'Post activity updates to a team\'s activity feed',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'postTeamActivities',
            description: 'Post team activities',
            parameters: {
                type: 'object',
                properties: {
                    teamId: { type: 'string', description: 'Team ID' },
                    type: { type: 'string', enum: ['UPDATE', 'MILESTONE', 'NOTE', 'MEMBER_JOINED', 'MEMBER_LEFT'], description: 'Activity type' },
                    content: { type: 'string', description: 'Activity content (max 5000 characters)' },
                    metadata: { type: 'object', description: 'Additional activity metadata' },
                    isPublic: { type: 'boolean', description: 'Whether activity is public (default: false)' },
                },
                required: ['teamId', 'type', 'content'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 30,
        examples: [],
    },
    {
        name: 'reportTeamKPIs',
        description: 'Generate and retrieve KPI reports for a team',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'reportTeamKPIs',
            description: 'Report team KPIs',
            parameters: {
                type: 'object',
                properties: {
                    teamId: { type: 'string', description: 'Team ID' },
                    metrics: {
                        type: 'array',
                        items: { type: 'string', enum: ['TASK_COMPLETION', 'TEAM_VELOCITY', 'MEMBER_CONTRIBUTION', 'COLLABORATION_SCORE'] },
                        description: 'Specific metrics to include',
                    },
                    startDate: { type: 'string', description: 'Start date for report (ISO8601)' },
                    endDate: { type: 'string', description: 'End date for report (ISO8601)' },
                    format: { type: 'string', enum: ['JSON', 'CSV', 'PDF'], description: 'Report format (default: JSON)' },
                },
                required: ['teamId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 60,
        rateLimit: 10,
        examples: [],
    },
    {
        name: 'publishTeamToMarketplace',
        description: 'Publish a team to the marketplace for discovery by other users',
        category: 'TASK_MANAGEMENT',
        isDefault: false,
        functionSchema: {
            name: 'publishTeamToMarketplace',
            description: 'Publish team to marketplace',
            parameters: {
                type: 'object',
                properties: {
                    teamId: { type: 'string', description: 'Team ID to publish' },
                    marketplaceVisibility: { type: 'string', enum: ['PUBLIC', 'LIMITED'], description: 'Marketplace visibility (default: PUBLIC)' },
                    tags: { type: 'array', items: { type: 'string' }, description: 'Marketplace tags for discovery' },
                },
                required: ['teamId'],
            },
        },
        deterministic: true,
        requiresAuth: true,
        timeout: 30,
        rateLimit: 5,
        examples: [],
    },
];
