// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/affiliates" | "/agentflox-ai" | "/agentflox-ai/agent-builder" | "/agentflox-ai/marketplace" | "/agentflox-ai/workflows" | "/careers" | "/contact" | "/docs" | "/docs/[...slug]" | "/learn/blog" | "/learn/community" | "/learn/demos" | "/learn/docs" | "/learn/help" | "/learn/support" | "/learn/tutorials" | "/learn/webinars" | "/legal" | "/legal/privacy" | "/legal/terms" | "/partners" | "/pricing" | "/product" | "/product/agents" | "/product/api" | "/product/automation" | "/product/collaboration" | "/product/integrations" | "/product/marketplace" | "/product/project-management" | "/product/security" | "/solutions/agencies" | "/solutions/construction" | "/solutions/education" | "/solutions/engineering" | "/solutions/enterprise" | "/solutions/finance" | "/solutions/hr" | "/solutions/marketing" | "/solutions/operations" | "/solutions/product-management" | "/solutions/project-management" | "/solutions/sales" | "/solutions/smb" | "/solutions/startups"
type PageRoutes = never
type LayoutRoutes = "/" | "/docs"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/affiliates": {}
  "/agentflox-ai": {}
  "/agentflox-ai/agent-builder": {}
  "/agentflox-ai/marketplace": {}
  "/agentflox-ai/workflows": {}
  "/careers": {}
  "/contact": {}
  "/docs": {}
  "/docs/[...slug]": { "slug": string[]; }
  "/learn/blog": {}
  "/learn/community": {}
  "/learn/demos": {}
  "/learn/docs": {}
  "/learn/help": {}
  "/learn/support": {}
  "/learn/tutorials": {}
  "/learn/webinars": {}
  "/legal": {}
  "/legal/privacy": {}
  "/legal/terms": {}
  "/partners": {}
  "/pricing": {}
  "/product": {}
  "/product/agents": {}
  "/product/api": {}
  "/product/automation": {}
  "/product/collaboration": {}
  "/product/integrations": {}
  "/product/marketplace": {}
  "/product/project-management": {}
  "/product/security": {}
  "/solutions/agencies": {}
  "/solutions/construction": {}
  "/solutions/education": {}
  "/solutions/engineering": {}
  "/solutions/enterprise": {}
  "/solutions/finance": {}
  "/solutions/hr": {}
  "/solutions/marketing": {}
  "/solutions/operations": {}
  "/solutions/product-management": {}
  "/solutions/project-management": {}
  "/solutions/sales": {}
  "/solutions/smb": {}
  "/solutions/startups": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/docs": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
