// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/affiliates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliates">> = Specific
  const handler = {} as typeof import("../../src/app/affiliates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agentflox-ai/agent-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentflox-ai/agent-builder">> = Specific
  const handler = {} as typeof import("../../src/app/agentflox-ai/agent-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agentflox-ai/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentflox-ai/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/agentflox-ai/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agentflox-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentflox-ai">> = Specific
  const handler = {} as typeof import("../../src/app/agentflox-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agentflox-ai/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agentflox-ai/workflows">> = Specific
  const handler = {} as typeof import("../../src/app/agentflox-ai/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/docs/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/blog">> = Specific
  const handler = {} as typeof import("../../src/app/learn/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/community">> = Specific
  const handler = {} as typeof import("../../src/app/learn/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/demos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/demos">> = Specific
  const handler = {} as typeof import("../../src/app/learn/demos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/docs">> = Specific
  const handler = {} as typeof import("../../src/app/learn/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/help">> = Specific
  const handler = {} as typeof import("../../src/app/learn/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/support">> = Specific
  const handler = {} as typeof import("../../src/app/learn/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/tutorials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/tutorials">> = Specific
  const handler = {} as typeof import("../../src/app/learn/tutorials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/webinars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/webinars">> = Specific
  const handler = {} as typeof import("../../src/app/learn/webinars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../src/app/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/legal/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/legal/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/legal/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/terms">> = Specific
  const handler = {} as typeof import("../../src/app/legal/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/agents">> = Specific
  const handler = {} as typeof import("../../src/app/product/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/api">> = Specific
  const handler = {} as typeof import("../../src/app/product/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/automation">> = Specific
  const handler = {} as typeof import("../../src/app/product/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/collaboration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/collaboration">> = Specific
  const handler = {} as typeof import("../../src/app/product/collaboration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/product/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/product/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product">> = Specific
  const handler = {} as typeof import("../../src/app/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/project-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/project-management">> = Specific
  const handler = {} as typeof import("../../src/app/product/project-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product/security">> = Specific
  const handler = {} as typeof import("../../src/app/product/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/agencies">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/construction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/construction">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/construction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/education">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/engineering/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/engineering">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/engineering/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/enterprise">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/finance">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/hr">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/operations">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/product-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/product-management">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/product-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/project-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/project-management">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/project-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/sales">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/smb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/smb">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/smb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/solutions/startups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/startups">> = Specific
  const handler = {} as typeof import("../../src/app/solutions/startups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
