import { ViewType } from "@/features/dashboard/components/modals/AddViewModal";
import type React from "react";
import {
  Activity,
  BarChart3,
  Calendar,
  CheckSquare,
  ClipboardList,
  Clock,
  FileCheck,
  FileText,
  FolderKanban,
  Hash,
  Image,
  Kanban,
  LayoutDashboard,
  LinkIcon,
  Map,
  MessageCircle,
  MessageSquare,
  Network,
  Package,
  PenTool,
  Sheet,
  Users,
  Video,
  Wrench,
} from "lucide-react";

export const viewConfig: Partial<
  Record<
    ViewType,
    {
      label: string;
      icon: React.ComponentType<{ className?: string; size?: number }>;
      description: string;
    }
  >
> = {
  OVERVIEW: { label: "Overview", icon: LayoutDashboard, description: "Overview of the space" },
  PROJECTS: { label: "Projects", icon: FolderKanban, description: "View and manage projects" },
  TEAMS: { label: "Teams", icon: Users, description: "View and manage teams" },
  DOCS: { label: "Docs", icon: FileText, description: "View and manage documents" },
  TASKS: { label: "Tasks", icon: CheckSquare, description: "View and manage tasks" },
  CHANNELS: { label: "Channels", icon: Hash, description: "View and manage channels" },
  PROPOSALS: { label: "Proposals", icon: FileCheck, description: "View and manage proposals" },
  TOOLS: { label: "Tools", icon: Wrench, description: "View and manage tools" },
  MATERIALS: { label: "Materials", icon: Package, description: "View and manage materials" },
  DASHBOARD: { label: "Dashboard", icon: LayoutDashboard, description: "Space dashboard" },
  ACTIVITY: { label: "Activity", icon: Activity, description: "Activity log" },
  POSTS: { label: "Posts", icon: MessageSquare, description: "Space posts" },
  DISCUSSIONS: { label: "Discussions", icon: MessageCircle, description: "Discussions" },
  LIST: { label: "List", icon: LayoutDashboard, description: "List view" },
  BOARD: { label: "Board", icon: Kanban, description: "Kanban board" },
  CALENDAR: { label: "Calendar", icon: Calendar, description: "Calendar view" },
  GANTT: { label: "Gantt", icon: Network, description: "Gantt chart" },
  DOC: { label: "Doc", icon: FileText, description: "Document" },
  FORM: { label: "Form", icon: LayoutDashboard, description: "Form" },
  TABLE: { label: "Table", icon: ClipboardList, description: "Table view" },
  TIMELINE: { label: "Timeline", icon: Clock, description: "Timeline view" },
  WORKLOAD: { label: "Workload", icon: BarChart3, description: "Workload view" },
  WHITEBOARD: { label: "Whiteboard", icon: PenTool, description: "Whiteboard" },
  MIND_MAP: { label: "Mind Map", icon: Network, description: "Mind map" },
  MAP: { label: "Map", icon: Map, description: "Map view" },
  PEOPLE: { label: "People", icon: Users, description: "People" },
  EMBED: { label: "Embed", icon: LinkIcon, description: "Embed view" },
  GOOGLE_CALENDAR: { label: "Google Calendar", icon: Calendar, description: "Google Calendar embed" },
  GOOGLE_DOCS: { label: "Google Docs", icon: FileText, description: "Google Docs embed" },
  GOOGLE_MAPS: { label: "Google Maps", icon: Map, description: "Google Maps embed" },
  GOOGLE_SLIDES: { label: "Google Slides", icon: LayoutDashboard, description: "Google Slides embed" },
  GOOGLE_FORMS: { label: "Google Forms", icon: LayoutDashboard, description: "Google Forms embed" },
  GOOGLE_DRIVE: { label: "Google Drive", icon: Sheet, description: "Google Drive embed" },
  SPREADSHEET: { label: "Sheet", icon: Sheet, description: "Spreadsheet" },
  FILE: { label: "File", icon: FileText, description: "File" },
  VIDEO: { label: "Video", icon: Video, description: "Video" },
  DESIGN: { label: "Design", icon: Image, description: "Design" },
  VIEWS: { label: "Views", icon: LayoutDashboard, description: "Views" },
  LOGS: { label: "Logs", icon: FileText, description: "Logs" },
  APPEAL: { label: "Appeal", icon: FileText, description: "Appeal" },
  GOVERNANCE: { label: "Governance", icon: FileText, description: "Governance" },
  ANALYTICS: { label: "Analytics", icon: BarChart3, description: "Analytics" },
  WAR_ROOM: { label: "War Room", icon: LayoutDashboard, description: "War Room" },
  MARKETPLACE: { label: "Marketplace", icon: LayoutDashboard, description: "Marketplace" },
  MEMBERS: { label: "Members", icon: Users, description: "Members" },
};
