import React from 'react';
import {
  Search,
  Link2,
  MonitorSmartphone,
  Workflow,
  Sparkles,
  Bot,
  Zap,
  Globe2,
  FileCode,
  Layers,
  FileText,
  Clock,
  Calendar,
  FolderSync,
  Bell,
  Eye,
  PlusCircle,
  FolderOpen,
  Send,
  MessageSquare,
  CheckCircle2,
} from 'lucide-react';

export type AppCenterCategorySection = 'integrations' | 'ai' | 'clickapps';

export type AppCenterCategoryItem = {
  id: string;
  label: string;
  section: AppCenterCategorySection;
  iconName: string;
  badge?: string;
};

export const APP_CENTER_CATEGORIES: AppCenterCategoryItem[] = [
  // Integrations section
  { id: 'all', label: 'All Apps', section: 'integrations', iconName: 'LayoutGrid' },
  { id: 'featured', label: 'Featured', section: 'integrations', iconName: 'Heart' },
  { id: 'analytics', label: 'Analytics', section: 'integrations', iconName: 'TrendingUp' },
  { id: 'calendar', label: 'Calendars', section: 'integrations', iconName: 'Calendar' },
  { id: 'storage', label: 'Cloud Storage', section: 'integrations', iconName: 'Cloud' },
  { id: 'communication', label: 'Communication', section: 'integrations', iconName: 'MessageSquare' },
  { id: 'search', label: 'Connected Search', section: 'integrations', iconName: 'Search' },
  { id: 'crm', label: 'CRM & Support', section: 'integrations', iconName: 'Briefcase' },
  { id: 'design', label: 'Design', section: 'integrations', iconName: 'Palette' },
  { id: 'development', label: 'Development', section: 'integrations', iconName: 'Code2' },
  { id: 'email', label: 'Email', section: 'integrations', iconName: 'Mail' },
  { id: 'finance', label: 'Finance & Accounting', section: 'integrations', iconName: 'CreditCard' },
  { id: 'knowledge', label: 'Knowledge Base', section: 'integrations', iconName: 'BookOpen' },
  { id: 'time', label: 'Time Tracking', section: 'integrations', iconName: 'Clock' },

  // AI section
  { id: 'connections', label: 'Connections', section: 'ai', iconName: 'Link2' },
  { id: 'mcp', label: 'MCP Servers', section: 'ai', iconName: 'Cpu', badge: 'New' },

  // ClickApps / AgentApps section
  { id: 'all_clickapps', label: 'All ClickApps', section: 'clickapps', iconName: 'Layers' },
  { id: 'ai_search', label: 'AI & Search', section: 'clickapps', iconName: 'Sparkles' },
  { id: 'collaboration', label: 'Collaboration', section: 'clickapps', iconName: 'Users' },
  { id: 'scheduling', label: 'Scheduling & Dates', section: 'clickapps', iconName: 'CalendarClock' },
  { id: 'sprints', label: 'Sprints', section: 'clickapps', iconName: 'Zap' },
  { id: 'tasks', label: 'Tasks', section: 'clickapps', iconName: 'CheckSquare' },
  { id: 'time_capacity', label: 'Time & Capacity', section: 'clickapps', iconName: 'Timer' },
];

export type AppFeature = {
  iconType: 'link' | 'panel' | 'search' | 'workflow' | 'sync' | 'bot' | 'zap';
  title: string;
  description: string;
  badge?: string;
};

export type AppCommand = {
  iconType: 'open' | 'create' | 'send' | 'sync' | 'search';
  title: string;
  description: string;
};

export type AppCenterItem = {
  id: string;
  name: string;
  description: string;
  fullDescription?: string;
  category: string;
  section: AppCenterCategorySection;
  isFeatured?: boolean;
  isMcp?: boolean;
  isOAuth?: boolean;
  oauthProvider?: string;
  builtBy?: string;
  docsUrl?: string;
  tags?: string[];
  features?: AppFeature[];
  commands?: AppCommand[];
  brandBg?: string;
  brandTextColor?: string;
  iconLetter?: string;
  iconSrc?: string;
};

export const APP_CENTER_ITEMS: AppCenterItem[] = [
  // FEATURED ITEMS
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Attach Dropbox files to tasks and search your cloud storage.',
    fullDescription: 'View, attach, and search files stored in Dropbox directly from Agentflox tasks and agent workflows.',
    category: 'storage',
    section: 'integrations',
    isFeatured: true,
    isOAuth: false,
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/dropbox',
    tags: ['Featured', 'Cloud Storage'],
    brandBg: '#0061FF',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Db',
    features: [
      {
        iconType: 'link',
        title: 'Preview Dropbox links in Agentflox',
        description: 'See live previews and rich metadata of attached Dropbox documents.',
      },
      {
        iconType: 'search',
        title: 'Personal Connected Search',
        description: 'Search Dropbox files directly from the global search bar.',
      },
      {
        iconType: 'panel',
        title: 'Dropbox File Browser in Tasks',
        description: 'Pick and attach cloud assets to work items without manual downloads.',
      },
    ],
    commands: [
      { iconType: 'open', title: 'Open Dropbox File', description: 'Quickly open linked cloud documents in a new tab.' },
      { iconType: 'create', title: 'Upload File to Dropbox', description: 'Export and upload task deliverables directly.' },
    ],
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'View Figma designs, create new files, and preview them—all directly within Agentflox.',
    fullDescription: 'View Figma designs, create new files, and preview them—all directly within Agentflox.',
    category: 'design',
    section: 'integrations',
    isFeatured: true,
    iconSrc: '/images/apps/figma-icon.webp',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/figma',
    tags: ['Featured', 'Design'],
    features: [
      {
        iconType: 'link',
        title: 'Preview Figma links in Agentflox',
        description: 'Link previews allow you to see live, synced visualizations of links directly in Agentflox.',
      },
      {
        iconType: 'panel',
        title: 'App panel in Task view',
        description: 'View links from Figma from a central place in Task view.',
      },
      {
        iconType: 'workflow',
        title: 'Figma Design Automations',
        description: 'Trigger agents when design frames or components are updated in Figma.',
        badge: 'New',
      },
    ],
    commands: [
      {
        iconType: 'open',
        title: 'Open Figma',
        description: 'Quickly launch Figma with just a couple of keystrokes.',
      },
      {
        iconType: 'create',
        title: 'Create New Figma File',
        description: 'Creates a new Figma file and opens it in a new tab.',
      },
    ],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Easily view and link GitHub PRs, commits, branches, and issues.',
    fullDescription: 'Connect GitHub repositories to track issues, pull requests, and commits directly in Agentflox.',
    category: 'development',
    section: 'integrations',
    isFeatured: true,
    isOAuth: true,
    oauthProvider: 'github',
    iconSrc: '/images/apps/github_logo_icon_229278.webp',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/github',
    tags: ['Featured', 'Development'],
    features: [
      {
        iconType: 'workflow',
        title: 'Automated PR & Issue Tracking',
        description: 'Sync pull requests, commits, and issue statuses automatically with tasks.',
      },
      {
        iconType: 'link',
        title: 'Preview GitHub Links',
        description: 'View live code diffs, branches, and review states directly inside tasks.',
      },
      {
        iconType: 'bot',
        title: 'AI Coding Agent Integrations',
        description: 'Allow Agentflox agents to create branches, commit code, and review PRs.',
        badge: 'New',
      },
    ],
    commands: [
      { iconType: 'open', title: 'Open Repository', description: 'Open your GitHub repository in a new tab.' },
      { iconType: 'create', title: 'Create Issue / PR', description: 'Create GitHub issues and pull requests from tasks.' },
    ],
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    description: 'Sync between Google Calendar and Agentflox for seamless scheduling.',
    fullDescription: 'Connect Google Calendar to schedule events, manage team availability, and sync deadlines.',
    category: 'calendar',
    section: 'integrations',
    isFeatured: true,
    isOAuth: true,
    oauthProvider: 'google_calendar',
    iconSrc: '/images/apps/Google_Calendar_Logo_512px.png',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/google-calendar',
    tags: ['Featured', 'Calendars'],
    features: [
      {
        iconType: 'sync',
        title: 'Two-Way Event Synchronization',
        description: 'Sync scheduled tasks and milestones directly to your Google Calendar.',
      },
      {
        iconType: 'workflow',
        title: 'Automated Meeting Triggers',
        description: 'Trigger autonomous agents before and after meetings to generate agendas and summaries.',
      },
    ],
    commands: [
      { iconType: 'create', title: 'Schedule Meeting', description: 'Book a Google Meet event directly from task view.' },
    ],
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    description: 'Easily attach, create, and search Google Drive files.',
    fullDescription: 'Connect Google Drive to access Docs, Sheets, Slides, and cloud files inside your workspace.',
    category: 'storage',
    section: 'integrations',
    isFeatured: true,
    isOAuth: true,
    oauthProvider: 'google_drive',
    iconSrc: '/images/apps/Google_Drive_Logo_512px.webp',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/google-drive',
    tags: ['Featured', 'Cloud Storage'],
    features: [
      {
        iconType: 'search',
        title: 'Google Drive Connected Search',
        description: 'Search documents across your personal and shared Google Drives directly in Agentflox.',
      },
      {
        iconType: 'link',
        title: 'Live Doc Previews',
        description: 'Embed and edit Google Docs, Sheets, and Slides in tasks without switching tabs.',
      },
    ],
    commands: [
      { iconType: 'create', title: 'Create New Google Doc', description: 'Generate a new doc and attach it to the current task.' },
      { iconType: 'open', title: 'Open in Google Drive', description: 'Quickly open file in Google Drive.' },
    ],
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Preview, create, and search Jira issues and sprints.',
    fullDescription: 'Two-way sync with Jira Software to track epics, sprints, stories, and bug reports seamlessly.',
    category: 'development',
    section: 'integrations',
    isFeatured: true,
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/jira',
    tags: ['Featured', 'Development', 'CRM & Support'],
    brandBg: '#0052CC',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Jira',
    features: [
      {
        iconType: 'link',
        title: 'Live Jira Issue Previews',
        description: 'Display real-time issue status, assignee, and priority inside tasks.',
      },
      {
        iconType: 'workflow',
        title: 'Jira Ticket Sync & Automations',
        description: 'Keep task statuses synchronized bidirectionally with Jira issues.',
      },
    ],
    commands: [
      { iconType: 'create', title: 'Create Jira Issue', description: 'Create and link Jira tickets from Agentflox.' },
      { iconType: 'search', title: 'Search Jira Backlog', description: 'Search tickets across active Jira projects.' },
    ],
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    description: 'Transform conversations into action by syncing Microsoft Teams messages.',
    fullDescription: 'Collaborate with your team seamlessly via Microsoft Teams channels, chats, and meetings.',
    category: 'communication',
    section: 'integrations',
    isFeatured: true,
    iconSrc: '/images/apps/Microsoft_Office_Teams_(2019–2025).svg.webp',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/teams',
    tags: ['Featured', 'Communication'],
    features: [
      {
        iconType: 'workflow',
        title: 'Teams Notifications & Bot Updates',
        description: 'Receive real-time agent notifications and task updates directly in MS Teams channels.',
      },
      {
        iconType: 'link',
        title: 'Turn Chats into Tasks',
        description: 'Convert messages into tracked tasks with one click.',
      },
    ],
    commands: [
      { iconType: 'send', title: 'Send Teams Message', description: 'Broadcast task updates to a selected Teams channel.' },
    ],
  },
  {
    id: 'outlook_calendar',
    name: 'Outlook Calendar',
    description: 'Sync between Outlook Calendar and Agentflox for easy scheduling.',
    fullDescription: 'Connect your Microsoft Outlook Calendar to synchronize events and manage team schedules.',
    category: 'calendar',
    section: 'integrations',
    isFeatured: true,
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/outlook',
    tags: ['Featured', 'Calendars'],
    brandBg: '#0078D4',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Out',
    features: [
      {
        iconType: 'sync',
        title: 'Two-Way Outlook Sync',
        description: 'Synchronize task deadlines and meetings with Microsoft Outlook.',
      },
    ],
    commands: [
      { iconType: 'create', title: 'Schedule Outlook Meeting', description: 'Create Outlook calendar invites.' },
    ],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Preview Salesforce links, create new leads, and sync customer deals.',
    fullDescription: 'Connect Salesforce CRM to access accounts, contacts, leads, and opportunities inside Agentflox.',
    category: 'crm',
    section: 'integrations',
    isFeatured: true,
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/salesforce',
    tags: ['Featured', 'CRM & Support'],
    brandBg: '#00A1E0',
    brandTextColor: '#FFFFFF',
    iconLetter: 'SF',
    features: [
      {
        iconType: 'link',
        title: 'Salesforce Record Previews',
        description: 'View real-time deal stage, amount, and contact details inside tasks.',
      },
      {
        iconType: 'workflow',
        title: 'CRM Automations',
        description: 'Trigger autonomous research and outreach workflows when deals update.',
      },
    ],
    commands: [
      { iconType: 'create', title: 'Create Salesforce Lead', description: 'Add new leads directly from customer interactions.' },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Bring Agentflox inside Slack with notifications, slash commands, and AI bots.',
    fullDescription: 'Receive notifications, trigger AI workforce agents, and update tasks from Slack channels.',
    category: 'communication',
    section: 'integrations',
    isFeatured: true,
    isOAuth: true,
    oauthProvider: 'slack',
    iconSrc: '/images/apps/slack-logo.png',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/slack',
    tags: ['Featured', 'Communication'],
    features: [
      {
        iconType: 'workflow',
        title: 'Interactive Channel Notifications',
        description: 'Get notified of critical task updates and agent execution logs.',
      },
      {
        iconType: 'bot',
        title: 'Slack Agent Assistant',
        description: 'Mention @Agentflox to query your workspace, summarize threads, or create tasks.',
      },
    ],
    commands: [
      { iconType: 'send', title: 'Post to Slack Channel', description: 'Send a message or execution summary to Slack.' },
    ],
  },
  {
    id: 'zoom',
    name: 'Zoom',
    description: 'Start Zoom calls with one click from tasks, meetings, and calendar events.',
    fullDescription: 'Connect Zoom to schedule video conferences, generate AI meeting transcripts, and sync recordings.',
    category: 'communication',
    section: 'integrations',
    isFeatured: true,
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/zoom',
    tags: ['Featured', 'Communication'],
    brandBg: '#2D8CFF',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Zm',
    features: [
      {
        iconType: 'link',
        title: 'One-Click Meeting Creation',
        description: 'Generate unique Zoom meeting links instantly inside tasks.',
      },
      {
        iconType: 'workflow',
        title: 'AI Recording & Summary',
        description: 'Automatically transcribe calls and extract action items into Agentflox tasks.',
      },
    ],
    commands: [
      { iconType: 'create', title: 'Start Instant Meeting', description: 'Launch a quick Zoom meeting.' },
    ],
  },

  // ALL APPS (INCLUDING MCP AND CATEGORY APPS)
  {
    id: 'aikido_security',
    name: 'Aikido Security',
    description: 'Put your application security on autopilot with instant vulnerability scanning.',
    category: 'development',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#5433FF',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Ai',
    tags: ['Development'],
  },
  {
    id: 'amplitude_mcp',
    name: 'Amplitude',
    description: 'Let AI query product analytics and metrics directly via MCP protocol.',
    category: 'analytics',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#1E61F8',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Amp',
    tags: ['Analytics', 'MCP'],
  },
  {
    id: 'atlassian_mcp',
    name: 'Atlassian',
    description: 'Let AI search and update work items across Jira and Confluence.',
    category: 'development',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#0052CC',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Atl',
    tags: ['Development', 'MCP'],
  },
  {
    id: 'azure_devops_sync',
    name: 'Azure DevOps Sync',
    description: "Boost your engineering team's efficiency with Azure Boards synchronization.",
    category: 'development',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#0078D7',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Az',
    tags: ['Development'],
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Link Bitbucket commits, branches, and pull requests to tasks.',
    category: 'development',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#205081',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Bb',
    tags: ['Development'],
  },
  {
    id: 'box',
    name: 'Box',
    description: 'Attach Box files to tasks, comments, and project briefs.',
    category: 'storage',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#0061D5',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Box',
    tags: ['Cloud Storage'],
  },
  {
    id: 'calendar_ical',
    name: 'Calendar subscription (iCal)',
    description: 'Add Agentflox tasks to your favorite calendar app via iCal feeds.',
    category: 'calendar',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#4A5568',
    brandTextColor: '#FFFFFF',
    iconLetter: 'iCal',
    tags: ['Calendars'],
  },
  {
    id: 'canny',
    name: 'Canny',
    description: 'Collect and prioritize user feedback from your customers.',
    category: 'crm',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#5046E5',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Can',
    tags: ['CRM & Support'],
  },
  {
    id: 'canny_mcp',
    name: 'Canny',
    description: 'Let AI collect, organize, and prioritize customer feature requests.',
    category: 'crm',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#5046E5',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Can',
    tags: ['CRM & Support', 'MCP'],
  },
  {
    id: 'canva_mcp',
    name: 'Canva',
    description: 'Let AI create designs from templates, generate banners, and export graphics.',
    category: 'design',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#00C4CC',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Cn',
    tags: ['Design', 'MCP'],
  },
  {
    id: 'chrome_extension',
    name: 'Chrome Extension',
    description: 'Bring Agentflox with you everywhere you browse the web.',
    category: 'development',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#EA4335',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Ch',
    tags: ['Development'],
  },
  {
    id: 'clay_mcp',
    name: 'Clay',
    description: 'Let AI search and enrich prospects, contacts, and company data.',
    category: 'crm',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#FF5C35',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Clay',
    tags: ['CRM & Support', 'MCP'],
  },
  {
    id: 'clockify',
    name: 'Clockify',
    description: 'Track time on Agentflox tasks and run detailed timesheet reports.',
    category: 'time',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#03A9F4',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Clk',
    tags: ['Time Tracking'],
  },
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Search and link Confluence knowledge base pages inside Agentflox.',
    category: 'knowledge',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#0052CC',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Conf',
    tags: ['Knowledge Base'],
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Preview key telemetry details and alerts from Datadog dashboards.',
    category: 'analytics',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#632CA6',
    brandTextColor: '#FFFFFF',
    iconLetter: 'DD',
    tags: ['Analytics'],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send Agentflox notifications and autonomous agent updates to Discord channels.',
    category: 'communication',
    section: 'integrations',
    iconSrc: '/images/apps/discord-icon.webp',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/discord',
    tags: ['Communication'],
  },
  {
    id: 'dropbox_mcp',
    name: 'Dropbox',
    description: 'Let AI search, upload, download, and organize files in Dropbox via MCP.',
    category: 'storage',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#0061FF',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Db',
    tags: ['Cloud Storage', 'MCP'],
  },
  {
    id: 'everhour',
    name: 'Everhour',
    description: 'Simplify time tracking and team budgeting with ClickUp and Everhour.',
    category: 'time',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#48BB78',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Eh',
    tags: ['Time Tracking'],
  },
  {
    id: 'freshdesk_sync',
    name: 'Freshdesk Sync',
    description: 'Connect Freshdesk support tickets directly to Agentflox tasks.',
    category: 'crm',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#00C9A7',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Fd',
    tags: ['CRM & Support'],
  },
  {
    id: 'github_mcp',
    name: 'GitHub',
    description: 'Let AI browse repos, manage issues, commit code, and review PRs via MCP.',
    category: 'development',
    section: 'ai',
    isMcp: true,
    iconSrc: '/images/apps/github_logo_icon_229278.webp',
    builtBy: 'Agentflox',
    tags: ['Development', 'MCP'],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Link GitLab activity, pipelines, merge requests, and commits directly to Agentflox.',
    category: 'development',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#FC6D26',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Gl',
    tags: ['Development'],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Search all your emails, send messages, and turn threads into tasks.',
    fullDescription: 'Connect Gmail to allow AI agents to draft replies, triage customer queries, and search email archives.',
    category: 'email',
    section: 'integrations',
    isOAuth: true,
    oauthProvider: 'gmail',
    iconSrc: '/images/apps/Gmail_Logo_512px.webp',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/gmail',
    tags: ['Email'],
    features: [
      {
        iconType: 'search',
        title: 'Connected Email Search',
        description: 'Find important conversations and attachments directly inside Agentflox.',
      },
      {
        iconType: 'bot',
        title: 'AI Email Assistant',
        description: 'Auto-categorize inbound emails and draft professional responses.',
      },
    ],
    commands: [
      { iconType: 'send', title: 'Send Email', description: 'Draft and send an email via connected Gmail account.' },
    ],
  },
  {
    id: 'gmail_email',
    name: 'Gmail Email',
    description: 'Send and receive emails without leaving your workspace.',
    category: 'email',
    section: 'integrations',
    iconSrc: '/images/apps/Gmail_Logo_512px.webp',
    builtBy: 'Agentflox',
    tags: ['Email'],
  },
  {
    id: 'google_chat',
    name: 'Google Chat',
    description: 'Setup Agentflox to post notifications to Google Chat spaces.',
    category: 'communication',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#00AC47',
    brandTextColor: '#FFFFFF',
    iconLetter: 'GC',
    tags: ['Communication'],
  },
  {
    id: 'harvest',
    name: 'Harvest',
    description: 'Automatically sync time tracked in Harvest with Agentflox work orders.',
    category: 'time',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#F36C00',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Hv',
    tags: ['Time Tracking'],
  },
  {
    id: 'hex_mcp',
    name: 'Hex',
    description: 'Search projects, explore data through notebooks, and run SQL queries.',
    category: 'analytics',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#201A3A',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Hex',
    tags: ['Analytics', 'MCP'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Integrate HubSpot Deal Workflows and contact updates with Agentflox.',
    category: 'crm',
    section: 'integrations',
    builtBy: 'Agentflox',
    brandBg: '#FF7A59',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Hub',
    tags: ['CRM & Support'],
  },
  {
    id: 'hubspot_mcp',
    name: 'HubSpot',
    description: 'Let AI search and manage contacts, companies, deals, and tickets via MCP.',
    category: 'crm',
    section: 'ai',
    isMcp: true,
    builtBy: 'Agentflox',
    brandBg: '#FF7A59',
    brandTextColor: '#FFFFFF',
    iconLetter: 'Hub',
    tags: ['CRM & Support', 'MCP'],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Sync pages and databases between Notion and Agentflox knowledge bases.',
    category: 'knowledge',
    section: 'integrations',
    iconSrc: '/images/apps/Notion_app_logo.png',
    builtBy: 'Agentflox',
    docsUrl: 'https://docs.agentflox.ai/integrations/notion',
    tags: ['Knowledge Base'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'Power your autonomous agents with GPT-4o, o1, and reasoning models.',
    category: 'development',
    section: 'ai',
    iconSrc: '/images/apps/openai-logo.png',
    builtBy: 'Agentflox',
    tags: ['Development', 'AI'],
  },
];
