ALTER TABLE "webhooks" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "webhooks" ADD COLUMN IF NOT EXISTS "headers" JSONB DEFAULT '[]';
ALTER TABLE "webhooks" ADD COLUMN IF NOT EXISTS "url_params" JSONB DEFAULT '[]';
ALTER TABLE "webhooks" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
