/**
 * Python sandbox preamble: Helper / LLM / datasets / Integration.
 * Uses HELPER_BRIDGE_URL + HELPER_BRIDGE_TOKEN when set (local bridge or public internal API).
 */
export function buildPythonSdkPreamble(): string {
  return [
    'import json',
    'import sys',
    'import os',
    'import urllib.request',
    'import urllib.error',
    '',
    'class _HelperResult:',
    '    def __init__(self, data):',
    '        self._data = data if isinstance(data, dict) else {"result": data}',
    '    def __getitem__(self, k): return self._data[k]',
    '    def get(self, k, d=None): return self._data.get(k, d)',
    '    def keys(self): return self._data.keys()',
    '    def __contains__(self, k): return k in self._data',
    '    def __repr__(self): return repr(self._data)',
    '    def __iter__(self): return iter(self._data)',
    '',
    'def _helper_http(name, args):',
    "    bridge = (os.environ.get('HELPER_BRIDGE_URL') or '').strip()",
    "    token = (os.environ.get('HELPER_BRIDGE_TOKEN') or '').strip()",
    '    if not bridge:',
    "        return {'__helper': name, '__input': args, 'status': 'error', 'text': '', 'tables': [], 'error': 'Helper bridge not configured'}",
    "    payload = json.dumps({'name': name, 'args': args}).encode('utf-8')",
    '    req = urllib.request.Request(',
    '        bridge,',
    '        data=payload,',
    "        headers={'Content-Type': 'application/json', 'Authorization': f'Bearer {token}'},",
    "        method='POST',",
    '    )',
    '    try:',
    '        with urllib.request.urlopen(req, timeout=180) as resp:',
    "            data = json.loads(resp.read().decode('utf-8'))",
    '    except urllib.error.HTTPError as e:',
    '        body = e.read().decode("utf-8", errors="replace") if e.fp else ""',
    '        try:',
    '            data = json.loads(body) if body else {}',
    '        except Exception:',
    "            data = {'status': 'error', 'error': body or str(e)}",
    '        if "status" not in data:',
    "            data = {'status': 'error', 'error': data.get('error') or str(e), **data}",
    '    if not isinstance(data, dict):',
    "        data = {'result': data}",
    '    return data',
    '',
    'class _Helper:',
    '    def __init__(self, name): self._name = name',
    '    def call(self, **kwargs):',
    '        return _HelperResult(_helper_http(self._name, kwargs))',
    '',
    'def Helper(name): return _Helper(name)',
    '',
    'class _LLMCompletions:',
    '    def __init__(self, model): self._model = model',
    '    def create(self, messages=None, **kwargs):',
    "        data = _helper_http('llm', {'model': self._model, 'messages': messages or [], **kwargs})",
    '        if data.get("status") == "error" and "choices" not in data:',
    "            err = data.get('error') or 'LLM failed'",
    "            return {'choices': [{'message': {'content': f'[LLM error: {err}]'}}], 'usage': {'total_tokens': 0}, 'error': err}",
    '        return data',
    '',
    'class _LLMChat:',
    '    def __init__(self, model): self.completions = _LLMCompletions(model)',
    '',
    'class _LLM:',
    '    def __init__(self, model): self.chat = _LLMChat(model)',
    '',
    "def LLM(model='gpt-4o-mini'): return _LLM(model)",
    '',
    'def prompt_completion(prompt, model=None):',
    "    data = _helper_http('prompt_completion', {'prompt': prompt, 'model': model})",
    "    return data.get('content') or data.get('answer') or data.get('error') or ''",
    '',
    'def run_step(step_id, input_data=None, **kwargs):',
    "    return _helper_http('run_step', {'step_name': step_id, 'params': input_data or kwargs})",
    '',
    'def insert_data(dataset_id, data):',
    "    return _helper_http('insert_data', {'dataset_id': dataset_id, 'data': data})",
    '',
    'def retrieve_data(dataset_id, page_size=None, include_fields=None):',
    "    return _helper_http('retrieve_data', {'dataset_id': dataset_id, 'page_size': page_size, 'include_fields': include_fields})",
    '',
    'def retrieve_all(dataset_id, page_size=1000, include_fields=None):',
    "    data = _helper_http('retrieve_all', {'dataset_id': dataset_id, 'page_size': page_size, 'include_fields': include_fields})",
    "    return data.get('data') if isinstance(data, dict) and 'data' in data else data",
    '',
    'def insert_temp_file(file_path_or_bytes, ext=None):',
    "    return _helper_http('insert_temp_file', {'file_path_or_bytes': file_path_or_bytes, 'ext': ext})",
    '',
    'class Integration:',
    '    def __init__(self, provider, account):',
    '        self.provider = provider',
    '        self.account = account',
    '    def api_call(self, method, url, body=None, headers=None, params=None):',
    "        return _helper_http('integration_api_call', {",
    "            'provider_name': self.provider, 'account_id': self.account,",
    "            'method': method, 'url': url, 'body': body, 'headers': headers, 'params': params,",
    '        })',
    '',
  ].join('\n');
}
