import { PrismaClient, PlanType, BillingPeriod } from '../src/generated/prisma';

const prisma = new PrismaClient();

type SeedProvider = 'OPENAI' | 'ANTHROPIC' | 'GOOGLE';
type CreditTier = 'FREE' | 'LOW' | 'MODERATE' | 'HIGH';

type SystemModelSeed = {
    slug: string;
    displayName: string;
    name: string;
    provider: SeedProvider;
    apiModelId: string;
    description: string;
    isDefault?: boolean;
    contextWindow: number;
    maxOutputTokens: number;
    maxTokens: number;
    creditsPer1kInput: number;
    creditsPer1kOutput: number;
    creditTier: CreditTier;
    inputFileTypes: string[];
    supportsThinking: boolean;
};

const VISION = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
const VISION_PDF = [...VISION, 'pdf'];

/** Approximate platform credit rates by tier (display/billing hints). */
const TIER_RATES: Record<CreditTier, { in: number; out: number }> = {
    FREE: { in: 0, out: 0 },
    LOW: { in: 0.15, out: 0.6 },
    MODERATE: { in: 1.25, out: 5 },
    HIGH: { in: 5, out: 25 },
};

function m(
    partial: Omit<SystemModelSeed, 'creditsPer1kInput' | 'creditsPer1kOutput' | 'name' | 'inputFileTypes' | 'maxTokens'> & {
        creditsPer1kInput?: number;
        creditsPer1kOutput?: number;
        name?: string;
        inputFileTypes?: string[];
        maxTokens?: number;
    },
): SystemModelSeed {
    const rates = TIER_RATES[partial.creditTier];
    return {
        ...partial,
        name: partial.name ?? partial.slug.replace(/-/g, '_'),
        creditsPer1kInput: partial.creditsPer1kInput ?? rates.in,
        creditsPer1kOutput: partial.creditsPer1kOutput ?? rates.out,
        inputFileTypes: partial.inputFileTypes ?? VISION,
        isDefault: partial.isDefault ?? false,
        maxTokens: partial.maxTokens ?? partial.maxOutputTokens,
    };
}

async function seedAiModels() {
    console.log('🌱 Seeding AI models...');

    // OpenAI / Anthropic / Google only (no OpenRouter aggregators).
    // Specs aligned to the product catalog list; apiModelId uses provider API ids where known.
    const systemModels: SystemModelSeed[] = [
        // ── Pick for me ──────────────────────────────────────────────
        m({
            slug: 'pick-performance-optimized',
            displayName: 'Performance-optimized Model',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.4',
            description: 'Pick for me — moderate-cost, long-context model for complex agentic work (maps to GPT 5.4).',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'pick-cost-optimized',
            displayName: 'Cost-optimized Model',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.4-mini',
            description: 'Pick for me — low-cost everyday model (maps to GPT 5.4 mini).',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),

        // ── OpenAI flagship / GPT-5 family ───────────────────────────
        m({
            slug: 'gpt-5-6',
            displayName: 'GPT 5.6',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.6',
            description: 'OpenAI GPT-5.6 — high capability multimodal model.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-6-sol',
            displayName: 'GPT 5.6 Sol',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.6-sol',
            description: 'OpenAI GPT-5.6 Sol variant.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-6-terra',
            displayName: 'GPT 5.6 Terra',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.6-terra',
            description: 'OpenAI GPT-5.6 Terra — moderate-cost long-context model.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-6-luna',
            displayName: 'GPT 5.6 Luna',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.6-luna',
            description: 'OpenAI GPT-5.6 Luna — cost-efficient long-context model.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-5-5',
            displayName: 'GPT 5.5',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.5',
            description: 'OpenAI GPT-5.5.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-5-2026-04-23',
            displayName: 'GPT 5.5 (2026-04-23)',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.5-2026-04-23',
            description: 'OpenAI GPT-5.5 dated snapshot.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-5-pro',
            displayName: 'GPT 5.5 Pro',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.5-pro',
            description: 'OpenAI GPT-5.5 Pro — highest capability GPT-5.5 tier.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-5-pro-2026-04-23',
            displayName: 'GPT 5.5 Pro (2026-04-23)',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.5-pro-2026-04-23',
            description: 'OpenAI GPT-5.5 Pro dated snapshot.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-4',
            displayName: 'GPT 5.4',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.4',
            description: 'OpenAI GPT-5.4.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-4-pro',
            displayName: 'GPT 5.4 Pro',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.4-pro',
            description: 'OpenAI GPT-5.4 Pro.',
            contextWindow: 1_050_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-4-mini',
            displayName: 'GPT 5.4 mini',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.4-mini',
            description: 'OpenAI GPT-5.4 mini — low-cost variant.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-5-4-nano',
            displayName: 'GPT 5.4 nano',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.4-nano',
            description: 'OpenAI GPT-5.4 nano — smallest GPT-5.4 tier.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-5-2',
            displayName: 'GPT 5.2',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.2',
            description: 'OpenAI GPT-5.2.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-2-pro',
            displayName: 'GPT 5.2 Pro',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.2-pro',
            description: 'OpenAI GPT-5.2 Pro.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-1',
            displayName: 'GPT 5.1',
            provider: 'OPENAI',
            apiModelId: 'gpt-5.1',
            description: 'OpenAI GPT-5.1.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5',
            displayName: 'GPT 5',
            provider: 'OPENAI',
            apiModelId: 'gpt-5',
            description: 'OpenAI GPT-5.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-pro',
            displayName: 'GPT 5 Pro',
            provider: 'OPENAI',
            apiModelId: 'gpt-5-pro',
            description: 'OpenAI GPT-5 Pro — extended output.',
            contextWindow: 400_000,
            maxOutputTokens: 272_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'gpt-5-mini',
            displayName: 'GPT 5 mini',
            provider: 'OPENAI',
            apiModelId: 'gpt-5-mini',
            description: 'OpenAI GPT-5 mini.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-5-nano',
            displayName: 'GPT 5 nano',
            provider: 'OPENAI',
            apiModelId: 'gpt-5-nano',
            description: 'OpenAI GPT-5 nano.',
            contextWindow: 400_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),

        // ── OpenAI GPT-4.1 / 4o / classic ─────────────────────────────
        m({
            slug: 'gpt-4-1',
            displayName: 'GPT 4.1 (latest)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4.1',
            description: 'OpenAI GPT-4.1 latest.',
            contextWindow: 1_047_576,
            maxOutputTokens: 32_768,
            creditTier: 'MODERATE',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-1-2025-04-14',
            displayName: 'GPT 4.1 (2025-04-14)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4.1-2025-04-14',
            description: 'OpenAI GPT-4.1 dated snapshot.',
            contextWindow: 1_047_576,
            maxOutputTokens: 32_768,
            creditTier: 'MODERATE',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-1-mini',
            displayName: 'GPT 4.1 mini (latest)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4.1-mini',
            description: 'OpenAI GPT-4.1 mini latest.',
            contextWindow: 1_047_576,
            maxOutputTokens: 32_768,
            maxTokens: 32_768,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-1-mini-2025-04-14',
            displayName: 'GPT 4.1 mini (2025-04-14)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4.1-mini-2025-04-14',
            description: 'OpenAI GPT-4.1 mini dated snapshot.',
            contextWindow: 1_047_576,
            maxOutputTokens: 32_768,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-1-nano',
            displayName: 'GPT 4.1 nano (latest)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4.1-nano',
            description: 'OpenAI GPT-4.1 nano latest.',
            contextWindow: 1_047_576,
            maxOutputTokens: 32_768,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-1-nano-2025-04-14',
            displayName: 'GPT 4.1 nano (2025-04-14)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4.1-nano-2025-04-14',
            description: 'OpenAI GPT-4.1 nano dated snapshot.',
            contextWindow: 1_047_576,
            maxOutputTokens: 32_768,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4o',
            displayName: 'GPT 4o',
            provider: 'OPENAI',
            apiModelId: 'gpt-4o',
            description: 'OpenAI GPT-4o multimodal.',
            contextWindow: 128_000,
            maxOutputTokens: 16_384,
            creditTier: 'MODERATE',
            creditsPer1kInput: 2.5,
            creditsPer1kOutput: 10,
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4o-2024-11-20',
            displayName: 'GPT 4o (2024-11-20)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4o-2024-11-20',
            description: 'OpenAI GPT-4o November 2024 snapshot.',
            contextWindow: 128_000,
            maxOutputTokens: 16_384,
            creditTier: 'MODERATE',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4o-2024-08-06',
            displayName: 'GPT 4o (2024-08-06)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4o-2024-08-06',
            description: 'OpenAI GPT-4o August 2024 snapshot.',
            contextWindow: 128_000,
            maxOutputTokens: 16_384,
            creditTier: 'MODERATE',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4o-2024-05-13',
            displayName: 'GPT 4o (2024-05-13)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4o-2024-05-13',
            description: 'OpenAI GPT-4o May 2024 snapshot.',
            contextWindow: 128_000,
            maxOutputTokens: 16_384,
            creditTier: 'MODERATE',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4o-mini',
            displayName: 'GPT 4o mini (latest)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4o-mini',
            description: 'Cost-optimized OpenAI GPT-4o mini (platform default).',
            isDefault: true,
            contextWindow: 128_000,
            maxOutputTokens: 16_384,
            creditTier: 'LOW',
            creditsPer1kInput: 0.15,
            creditsPer1kOutput: 0.6,
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4o-mini-2024-07-18',
            displayName: 'GPT 4o mini (2024-07-18)',
            provider: 'OPENAI',
            apiModelId: 'gpt-4o-mini-2024-07-18',
            description: 'OpenAI GPT-4o mini July 2024 snapshot.',
            contextWindow: 128_000,
            maxOutputTokens: 16_384,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-turbo',
            displayName: 'GPT 4 Turbo',
            provider: 'OPENAI',
            apiModelId: 'gpt-4-turbo',
            description: 'OpenAI GPT-4 Turbo.',
            contextWindow: 128_000,
            maxOutputTokens: 4_096,
            creditTier: 'HIGH',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4',
            displayName: 'GPT 4',
            provider: 'OPENAI',
            apiModelId: 'gpt-4',
            description: 'OpenAI GPT-4.',
            contextWindow: 8_192,
            maxOutputTokens: 8_192,
            creditTier: 'HIGH',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-4-0613',
            displayName: 'GPT 4 0613',
            provider: 'OPENAI',
            apiModelId: 'gpt-4-0613',
            description: 'OpenAI GPT-4 0613 snapshot.',
            contextWindow: 8_192,
            maxOutputTokens: 8_192,
            creditTier: 'HIGH',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-3-5-turbo',
            displayName: 'GPT 3.5',
            provider: 'OPENAI',
            apiModelId: 'gpt-3.5-turbo',
            description: 'OpenAI GPT-3.5 Turbo.',
            contextWindow: 16_385,
            maxOutputTokens: 4_096,
            creditTier: 'LOW',
            supportsThinking: false,
            inputFileTypes: [],
        }),
        m({
            slug: 'gpt-3-5-turbo-16k',
            displayName: 'GPT 3.5 16k',
            provider: 'OPENAI',
            apiModelId: 'gpt-3.5-turbo-16k',
            description: 'OpenAI GPT-3.5 Turbo 16k.',
            contextWindow: 16_385,
            maxOutputTokens: 4_096,
            creditTier: 'LOW',
            supportsThinking: false,
            inputFileTypes: [],
        }),
        m({
            slug: 'gpt-3-5-turbo-1106',
            displayName: 'GPT 3.5 1106',
            provider: 'OPENAI',
            apiModelId: 'gpt-3.5-turbo-1106',
            description: 'OpenAI GPT-3.5 Turbo 1106.',
            contextWindow: 16_385,
            maxOutputTokens: 4_096,
            creditTier: 'LOW',
            supportsThinking: false,
            inputFileTypes: [],
        }),
        m({
            slug: 'gpt-oss-120b',
            displayName: 'gpt-oss-120b (Bedrock)',
            provider: 'OPENAI',
            apiModelId: 'gpt-oss-120b',
            description: 'Open-weight GPT-OSS 120B (Bedrock-compatible id).',
            contextWindow: 128_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),
        m({
            slug: 'gpt-oss-20b',
            displayName: 'gpt-oss-20b (Bedrock)',
            provider: 'OPENAI',
            apiModelId: 'gpt-oss-20b',
            description: 'Open-weight GPT-OSS 20B (Bedrock-compatible id).',
            contextWindow: 128_000,
            maxOutputTokens: 128_000,
            creditTier: 'LOW',
            supportsThinking: false,
        }),

        // ── OpenAI reasoning (o-series) ──────────────────────────────
        m({
            slug: 'o1',
            displayName: 'o1 (latest)',
            provider: 'OPENAI',
            apiModelId: 'o1',
            description: 'OpenAI o1 reasoning model.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'o1-2024-12-17',
            displayName: 'o1 (2024-12-17)',
            provider: 'OPENAI',
            apiModelId: 'o1-2024-12-17',
            description: 'OpenAI o1 dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'o1-pro',
            displayName: 'o1-pro',
            provider: 'OPENAI',
            apiModelId: 'o1-pro',
            description: 'OpenAI o1-pro.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'o3',
            displayName: 'o3 (latest)',
            provider: 'OPENAI',
            apiModelId: 'o3',
            description: 'OpenAI o3 reasoning model.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'o3-2025-04-16',
            displayName: 'o3 (2025-04-16)',
            provider: 'OPENAI',
            apiModelId: 'o3-2025-04-16',
            description: 'OpenAI o3 dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'MODERATE',
            supportsThinking: true,
        }),
        m({
            slug: 'o3-pro',
            displayName: 'o3-pro (latest)',
            provider: 'OPENAI',
            apiModelId: 'o3-pro',
            description: 'OpenAI o3-pro.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'o3-pro-2025-06-10',
            displayName: 'o3-pro (2025-06-10)',
            provider: 'OPENAI',
            apiModelId: 'o3-pro-2025-06-10',
            description: 'OpenAI o3-pro dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'HIGH',
            supportsThinking: true,
        }),
        m({
            slug: 'o3-mini',
            displayName: 'o3-mini (latest)',
            provider: 'OPENAI',
            apiModelId: 'o3-mini',
            description: 'OpenAI o3-mini.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'LOW',
            supportsThinking: true,
        }),
        m({
            slug: 'o3-mini-2025-01-31',
            displayName: 'o3-mini (2025-01-31)',
            provider: 'OPENAI',
            apiModelId: 'o3-mini-2025-01-31',
            description: 'OpenAI o3-mini dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'LOW',
            supportsThinking: true,
        }),
        m({
            slug: 'o4-mini',
            displayName: 'o4-mini (latest)',
            provider: 'OPENAI',
            apiModelId: 'o4-mini',
            description: 'OpenAI o4-mini.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'LOW',
            supportsThinking: true,
        }),
        m({
            slug: 'o4-mini-2025-04-16',
            displayName: 'o4-mini (2025-04-16)',
            provider: 'OPENAI',
            apiModelId: 'o4-mini-2025-04-16',
            description: 'OpenAI o4-mini dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 100_000,
            creditTier: 'LOW',
            supportsThinking: true,
        }),

        // ── Anthropic Claude ─────────────────────────────────────────
        m({
            slug: 'claude-fable-5',
            displayName: 'Claude Fable 5',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-fable-5',
            description: 'Anthropic Claude Fable 5 — adaptive thinking for complex tasks.',
            contextWindow: 1_000_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            creditsPer1kInput: 2.75,
            creditsPer1kOutput: 13.75,
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-5',
            displayName: 'Claude Opus 5',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-5',
            description: 'Anthropic Claude Opus 5.',
            contextWindow: 1_000_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-8',
            displayName: 'Claude Opus 4.8',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-8',
            description: 'Anthropic Claude Opus 4.8.',
            contextWindow: 1_000_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-7',
            displayName: 'Claude Opus 4.7',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-7',
            description: 'Anthropic Claude Opus 4.7.',
            contextWindow: 1_000_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-6',
            displayName: 'Claude Opus 4.6',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-6',
            description: "Anthropic's Opus model with adaptive thinking. Good performance on complex reasoning, coding, and agentic tasks.",
            contextWindow: 1_000_000,
            maxOutputTokens: 128_000,
            creditTier: 'HIGH',
            creditsPer1kInput: 2.75,
            creditsPer1kOutput: 13.75,
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-5',
            displayName: 'Claude Opus 4.5',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-5',
            description: 'Anthropic Claude Opus 4.5.',
            contextWindow: 200_000,
            maxOutputTokens: 64_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-1',
            displayName: 'Claude Opus 4.1 (latest)',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-1',
            description: 'Anthropic Claude Opus 4.1 latest.',
            contextWindow: 200_000,
            maxOutputTokens: 32_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-1-20250805',
            displayName: 'Claude Opus 4.1 (20250805)',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-1-20250805',
            description: 'Anthropic Claude Opus 4.1 dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 32_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4',
            displayName: 'Claude Opus 4 (latest)',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4',
            description: 'Anthropic Claude Opus 4 latest.',
            contextWindow: 200_000,
            maxOutputTokens: 32_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-opus-4-20250514',
            displayName: 'Claude Opus 4 (20250514)',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-opus-4-20250514',
            description: 'Anthropic Claude Opus 4 dated snapshot.',
            contextWindow: 200_000,
            maxOutputTokens: 32_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-sonnet-5',
            displayName: 'Claude Sonnet 5',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-sonnet-5',
            description: 'Anthropic Claude Sonnet 5.',
            contextWindow: 1_000_000,
            maxOutputTokens: 128_000,
            creditTier: 'MODERATE',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-sonnet-4-6',
            displayName: 'Claude Sonnet 4.6',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-sonnet-4-6',
            description: 'Anthropic Claude Sonnet 4.6.',
            contextWindow: 1_000_000,
            maxOutputTokens: 64_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-sonnet-4-5',
            displayName: 'Claude Sonnet 4.5 (latest)',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-sonnet-4-5',
            description: 'Anthropic Claude Sonnet 4.5 latest.',
            contextWindow: 200_000,
            maxOutputTokens: 64_000,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'claude-haiku-4-5',
            displayName: 'Claude Haiku 4.5',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-haiku-4-5',
            description: 'Anthropic Claude Haiku 4.5 — fast and efficient.',
            contextWindow: 200_000,
            maxOutputTokens: 64_000,
            creditTier: 'MODERATE',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'claude-3-5-sonnet',
            displayName: 'Claude 3.5 Sonnet',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-3-5-sonnet-20240620',
            description: 'Anthropic Claude 3.5 Sonnet.',
            contextWindow: 200_000,
            maxOutputTokens: 8_192,
            creditTier: 'HIGH',
            creditsPer1kInput: 3,
            creditsPer1kOutput: 15,
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'claude-3-opus',
            displayName: 'Claude 3 Opus',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-3-opus-20240229',
            description: 'Anthropic Claude 3 Opus.',
            contextWindow: 200_000,
            maxOutputTokens: 4_096,
            creditTier: 'HIGH',
            creditsPer1kInput: 15,
            creditsPer1kOutput: 75,
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'claude-3-haiku',
            displayName: 'Claude 3 Haiku',
            provider: 'ANTHROPIC',
            apiModelId: 'claude-3-haiku-20240307',
            description: 'Anthropic Claude 3 Haiku.',
            contextWindow: 200_000,
            maxOutputTokens: 4_096,
            creditTier: 'LOW',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),

        // ── Google Gemini ────────────────────────────────────────────
        m({
            slug: 'gemini-3-1-pro-preview',
            displayName: 'Gemini 3.1 Pro Preview',
            provider: 'GOOGLE',
            apiModelId: 'gemini-3.1-pro-preview',
            description: 'Google Gemini 3.1 Pro Preview.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_536,
            creditTier: 'HIGH',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'gemini-3-6-flash',
            displayName: 'Gemini 3.6 Flash',
            provider: 'GOOGLE',
            apiModelId: 'gemini-3.6-flash',
            description: 'Google Gemini 3.6 Flash.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_536,
            creditTier: 'MODERATE',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-3-5-flash',
            displayName: 'Gemini 3.5 Flash',
            provider: 'GOOGLE',
            apiModelId: 'gemini-3.5-flash',
            description: 'Google Gemini 3.5 Flash.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_536,
            creditTier: 'MODERATE',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-3-5-flash-lite',
            displayName: 'Gemini 3.5 Flash Lite',
            provider: 'GOOGLE',
            apiModelId: 'gemini-3.5-flash-lite',
            description: 'Google Gemini 3.5 Flash Lite.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_536,
            creditTier: 'LOW',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-3-flash-preview',
            displayName: 'Gemini 3 Flash Preview',
            provider: 'GOOGLE',
            apiModelId: 'gemini-3-flash-preview',
            description: 'Google Gemini 3 Flash Preview.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_536,
            creditTier: 'LOW',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-2-5-pro',
            displayName: 'Gemini 2.5 Pro (latest)',
            provider: 'GOOGLE',
            apiModelId: 'gemini-2.5-pro',
            description: 'Google Gemini 2.5 Pro latest.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_535,
            creditTier: 'MODERATE',
            inputFileTypes: VISION_PDF,
            supportsThinking: true,
        }),
        m({
            slug: 'gemini-2-5-flash',
            displayName: 'Gemini 2.5 Flash (latest)',
            provider: 'GOOGLE',
            apiModelId: 'gemini-2.5-flash',
            description: 'Google Gemini 2.5 Flash latest.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_535,
            creditTier: 'LOW',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-2-5-flash-lite',
            displayName: 'Gemini 2.5 Flash Lite',
            provider: 'GOOGLE',
            apiModelId: 'gemini-2.5-flash-lite',
            description: 'Google Gemini 2.5 Flash Lite.',
            contextWindow: 1_048_576,
            maxOutputTokens: 65_535,
            creditTier: 'LOW',
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-1-5-pro',
            displayName: 'Gemini 1.5 Pro',
            provider: 'GOOGLE',
            apiModelId: 'gemini-1.5-pro',
            description: 'Google Gemini 1.5 Pro.',
            contextWindow: 2_000_000,
            maxOutputTokens: 8_192,
            creditTier: 'MODERATE',
            creditsPer1kInput: 1.25,
            creditsPer1kOutput: 5,
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-1-5-flash',
            displayName: 'Gemini 1.5 Flash',
            provider: 'GOOGLE',
            apiModelId: 'gemini-1.5-flash',
            description: 'Google Gemini 1.5 Flash.',
            contextWindow: 1_000_000,
            maxOutputTokens: 8_192,
            creditTier: 'LOW',
            creditsPer1kInput: 0.075,
            creditsPer1kOutput: 0.3,
            inputFileTypes: VISION_PDF,
            supportsThinking: false,
        }),
        m({
            slug: 'gemini-vision',
            displayName: 'Gemini Vision',
            provider: 'GOOGLE',
            apiModelId: 'gemini-pro-vision',
            description: 'Google Gemini Vision.',
            contextWindow: 12_288,
            maxOutputTokens: 4_096,
            creditTier: 'MODERATE',
            inputFileTypes: VISION,
            supportsThinking: false,
        }),
    ];

    for (const model of systemModels) {
        const id = `seed_${model.slug.replace(/-/g, '_')}`;
        const existing =
            (await prisma.aiModel.findUnique({ where: { id } })) ??
            (await prisma.aiModel.findFirst({
                where: { slug: model.slug, isSystem: true },
            }));

        const data = {
            slug: model.slug,
            displayName: model.displayName,
            name: model.name,
            provider: model.provider,
            apiModelId: model.apiModelId,
            version: '1.0.0',
            description: model.description,
            isSystem: true,
            isCustom: false,
            isDefault: Boolean(model.isDefault),
            isActive: true,
            contextWindow: model.contextWindow,
            maxOutputTokens: model.maxOutputTokens,
            maxTokens: model.maxTokens,
            creditsPer1kInput: model.creditsPer1kInput,
            creditsPer1kOutput: model.creditsPer1kOutput,
            creditTier: model.creditTier,
            inputFileTypes: model.inputFileTypes,
            supportsThinking: model.supportsThinking,
        };

        if (existing) {
            await prisma.aiModel.update({
                where: { id: existing.id },
                data,
            });
        } else {
            await prisma.aiModel.create({
                data: { id, ...data },
            });
        }
    }

    await prisma.$executeRaw`
      UPDATE ai_models SET is_default = false WHERE is_default = true AND slug <> 'gpt-4o-mini'
    `;
    await prisma.$executeRaw`
      UPDATE ai_models SET is_default = true WHERE slug = 'gpt-4o-mini' AND is_system = true
    `;

    console.log(`✅ Seeded ${systemModels.length} system AI models (default: gpt-4o-mini)`);
}

async function seedPlans() {
    const freePlan = await prisma.plan.create({
        data: {
            name: 'FREE',
            displayName: 'Free Plan',
            description: 'Perfect for getting started',
            slug: 'free',
            planType: PlanType.FREE,
            billingPeriod: BillingPeriod.MONTHLY,
            price: 0,
            currency: 'USD',
            trialDays: 0,
            isActive: true,
            isFeatured: false,
            sortOrder: 1,
            feature: {
                create: {
                    name: 'FREE_Feature',
                    description: [],
                    maxProjects: 3,
                    maxTeams: 1,
                    maxApplicationRequests: 100,
                    maxCredits: 1000,
                    maxTokens: 10000,
                    maxSpaces: 3,
                    maxWorkspaces: 1,
                    maxExecutions: 10,
                    maxConcurrentRuns: 2,
                    maxSupabaseStorage: 1,
                    maxRedisStorage: 0,
                },
            },
        },
    });

    const proPlan = await prisma.plan.create({
        data: {
            name: 'PRO',
            displayName: 'Pro Plan',
            description: 'For growing teams and businesses',
            slug: 'pro',
            planType: PlanType.PROFESSIONAL,
            billingPeriod: BillingPeriod.MONTHLY,
            price: 29.99,
            currency: 'USD',
            trialDays: 14,
            isActive: true,
            isFeatured: true,
            sortOrder: 2,
            feature: {
                create: {
                    name: 'PRO_Feature',
                    description: [],
                    maxProjects: 50,
                    maxTeams: 10,
                    maxApplicationRequests: 10000,
                    maxCredits: 50000,
                    maxTokens: 500000,
                    maxSpaces: 50,
                    maxWorkspaces: 5,
                    maxExecutions: 500,
                    maxConcurrentRuns: 5,
                    maxSupabaseStorage: 50,
                    maxRedisStorage: 1,
                },
            },
        },
    });

    const enterprisePlan = await prisma.plan.create({
        data: {
            name: 'ENTERPRISE',
            displayName: 'Enterprise Plan',
            description: 'For large organizations with advanced needs',
            slug: 'enterprise',
            planType: PlanType.ENTERPRISE,
            billingPeriod: BillingPeriod.MONTHLY,
            price: 99.99,
            currency: 'USD',
            trialDays: 30,
            isActive: true,
            isFeatured: true,
            sortOrder: 3,
            feature: {
                create: {
                    name: 'ENTERPRISE_Feature',
                    description: [],
                    maxProjects: -1,
                    maxTeams: -1,
                    maxApplicationRequests: -1,
                    maxCredits: -1,
                    maxTokens: -1,
                    maxSpaces: -1,
                    maxWorkspaces: -1,
                    maxExecutions: -1,
                    maxConcurrentRuns: 10,
                    maxSupabaseStorage: -1,
                    maxRedisStorage: -1,
                },
            },
        },
    });

    console.log('✅ Created plans:');
    console.log(`  - ${freePlan.displayName} (${freePlan.name})`);
    console.log(`  - ${proPlan.displayName} (${proPlan.name})`);
    console.log(`  - ${enterprisePlan.displayName} (${enterprisePlan.name})`);
}

async function main() {
    console.log('🌱 Starting database seed...');

    const existingPlans = await prisma.plan.count();
    if (existingPlans > 0) {
        console.log('⚠️  Plans already exist. Skipping plan seed.');
    } else {
        await seedPlans();
    }

    await seedAiModels();
    console.log('🎉 Seed completed successfully!');
}

main()
    .catch((e) => {
        console.error('❌ Seed failed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
