ALTER TABLE "ai_models" ADD COLUMN IF NOT EXISTS "max_tokens" INTEGER;
ALTER TABLE "ai_models" ADD COLUMN IF NOT EXISTS "temperature" DOUBLE PRECISION;
ALTER TABLE "ai_models" ADD COLUMN IF NOT EXISTS "RPM" INTEGER;
ALTER TABLE "ai_models" ADD COLUMN IF NOT EXISTS "RPD" INTEGER;
ALTER TABLE "ai_models" ADD COLUMN IF NOT EXISTS "TPM" INTEGER;
ALTER TABLE "ai_models" ADD COLUMN IF NOT EXISTS "TPD" INTEGER;
