import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  ArrowRightToLine,
  Bell,
  Bot,
  Box,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarX,
  CheckCircle2,
  CirclePlus,
  Clock,
  Compass,
  FileCheck,
  FileCode,
  FileText,
  Flame,
  Flag,
  FolderPlus,
  GitBranch,
  GitPullRequest,
  Layers,
  Link2,
  ListOrdered,
  Mail,
  MailPlus,
  MessageCircle,
  MessageSquare,
  PhoneCall,
  RefreshCw,
  Send,
  Settings2,
  Share2,
  Sparkles,
  SquarePen,
  Target,
  UserCheck,
  UserPlus,
  Users,
  Webhook,
} from "lucide-react";
import type { AutomationActionTypeV1 } from "./actionCatalog";
import type { AutomationTriggerTypeV1 } from "./triggerCatalog";

export type BrowseSectionId =
  | "popular"
  | "development"
  | "marketing"
  | "professionalServices"
  | "projectManagement"
  | "assignees"
  | "creation"
  | "dates"
  | "move"
  | "statuses"
  | "taskTypes"
  | "webhook"
  | "bugsnag"
  | "calendly"
  | "email"
  | "github"
  | "google-calendar"
  | "google-drive"
  | "hubspot"
  | "slack"
  | "twilio";

export type BrowseTemplate = {
  id: string;
  title: string;
  description: string;
  triggerIcon: LucideIcon;
  actionIcon: LucideIcon;
  badge?: "popular" | "agent" | "new";
  sections: BrowseSectionId[];
  mode: "classic" | "agent";
  triggerType: AutomationTriggerTypeV1;
  actionType: AutomationActionTypeV1;
  triggerConfig?: Record<string, any>;
  actionConfig?: Record<string, any>;
  comingSoon?: boolean;
  applyTemplateId?: "auto-assign" | "update-status-on-create" | "launch-ai-on-create";
};

export const BROWSE_TEMPLATES: BrowseTemplate[] = [
  // ─── POPULAR ─────────────────────────────────────────────────────────────
  {
    id: "kick-off-scoped",
    title: "Kick off tasks fully scoped",
    description: "Auto-fill key custom fields the moment work is created so every task starts with the right context.",
    triggerIcon: CirclePlus,
    actionIcon: SquarePen,
    badge: "popular",
    sections: ["popular", "creation", "projectManagement"],
    mode: "agent",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "DO_ANYTHING_WITH_AI",
    applyTemplateId: "launch-ai-on-create",
  },
  {
    id: "share-status-updates",
    title: "Share status updates instantly",
    description: "Post smart status comments so stakeholders always know what changed and what happens next.",
    triggerIcon: Target,
    actionIcon: MessageSquare,
    badge: "popular",
    sections: ["popular", "statuses", "professionalServices"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "schedule-super-agent-runs",
    title: "Schedule Super Agent runs",
    description: "Launch Super Agents on a recurring schedule to handle routine operations without manual follow-ups.",
    triggerIcon: CalendarClock,
    actionIcon: Bot,
    badge: "agent",
    sections: ["popular", "dates", "projectManagement"],
    mode: "agent",
    triggerType: "EVERY_SCHEDULED_TIME",
    actionType: "DO_ANYTHING_WITH_AI",
  },
  {
    id: "triage-new-work-super-agents",
    title: "Triage new work with Super Agents",
    description: "Route every new task through Super Agents to organize details, suggest priorities, and keep intake clean.",
    triggerIcon: CirclePlus,
    actionIcon: Bot,
    badge: "agent",
    sections: ["popular", "creation", "assignees"],
    mode: "agent",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "DO_ANYTHING_WITH_AI",
    applyTemplateId: "launch-ai-on-create",
  },
  {
    id: "polished-progress-emails",
    title: "Send polished progress emails",
    description: "Automatically notify clients and teams when statuses change so updates stay timely and consistent.",
    triggerIcon: Target,
    actionIcon: Mail,
    badge: "popular",
    sections: ["popular", "marketing", "statuses", "email"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "sync-systems-realtime",
    title: "Sync systems in real time",
    description: "Trigger webhooks from custom field updates to keep downstream tools aligned automatically.",
    triggerIcon: SquarePen,
    actionIcon: Webhook,
    badge: "popular",
    sections: ["popular", "webhook", "development"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "CALL_WEBHOOK",
  },

  // ─── DEVELOPMENT ─────────────────────────────────────────────────────────
  {
    id: "dev-keep-updates-flowing",
    title: "Keep engineering updates flowing",
    description: "Post status comments automatically so developers and PMs stay aligned on ticket progress.",
    triggerIcon: Target,
    actionIcon: MessageSquare,
    badge: "popular",
    sections: ["development", "statuses", "creation"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "dev-route-tickets-expertise",
    title: "Route tickets by expertise",
    description: "Assign work based on technical context to match issues with the right engineers faster.",
    triggerIcon: SquarePen,
    actionIcon: Users,
    badge: "popular",
    sections: ["development", "assignees"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_ASSIGNEES",
    applyTemplateId: "auto-assign",
  },
  {
    id: "dev-close-loop-merge",
    title: "Close the loop after merge",
    description: "Move work forward when pull requests merge so delivery status always reflects reality.",
    triggerIcon: GitPullRequest,
    actionIcon: Target,
    sections: ["development", "github", "statuses"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_UPDATED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "dev-mirror-work-github",
    title: "Mirror work to GitHub instantly",
    description: "Create GitHub issues from new ClickUp tasks so engineering execution starts without delay.",
    triggerIcon: CirclePlus,
    actionIcon: GitBranch,
    sections: ["development", "github", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "dev-sync-status-sprint",
    title: "Sync status to sprint stage",
    description: "Update status as tasks move between sprint lists to keep boards accurate automatically.",
    triggerIcon: ArrowRightToLine,
    actionIcon: Target,
    sections: ["development", "move", "statuses"],
    mode: "classic",
    triggerType: "MOVE_TO_LIST",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "dev-escalate-critical-incidents",
    title: "Escalate critical incidents",
    description: "Add the right followers on critical priority changes so response teams are alerted immediately.",
    triggerIcon: Flag,
    actionIcon: UserPlus,
    sections: ["development", "assignees", "dates"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "UPDATE_FOLLOWERS",
  },

  // ─── MARKETING ───────────────────────────────────────────────────────────
  {
    id: "mkt-launch-campaigns-consistency",
    title: "Launch campaigns with consistency",
    description: "Apply campaign templates automatically so every launch follows the same high-quality playbook.",
    triggerIcon: CirclePlus,
    actionIcon: Layers,
    badge: "popular",
    sections: ["marketing", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "APPLY_TEMPLATE",
  },
  {
    id: "mkt-broadcast-momentum",
    title: "Broadcast campaign momentum",
    description: "Send automatic status emails to keep partners and stakeholders aligned on progress.",
    triggerIcon: Target,
    actionIcon: Mail,
    badge: "popular",
    sections: ["marketing", "statuses", "email"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "mkt-route-work-channel",
    title: "Route work by channel",
    description: "Assign tasks by campaign type or channel so specialists get the right work instantly.",
    triggerIcon: SquarePen,
    actionIcon: Users,
    sections: ["marketing", "assignees"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "mkt-prioritize-launch-impact",
    title: "Prioritize by launch impact",
    description: "Adjust priority as campaigns evolve so the highest-impact work stays on top.",
    triggerIcon: SquarePen,
    actionIcon: Flag,
    sections: ["marketing", "statuses"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_PRIORITY",
  },
  {
    id: "mkt-document-milestones",
    title: "Document key campaign milestones",
    description: "Add milestone comments from tag updates to maintain a clear narrative across launches.",
    triggerIcon: Flag,
    actionIcon: MessageSquare,
    sections: ["marketing", "creation"],
    mode: "classic",
    triggerType: "TAG_ADDED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "mkt-protect-deadlines",
    title: "Protect launch deadlines",
    description: "Notify the right owners when dates shift so launches stay coordinated and on time.",
    triggerIcon: Calendar,
    actionIcon: Bell,
    sections: ["marketing", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_CHANGED",
    actionType: "ADD_COMMENT",
  },

  // ─── PROFESSIONAL SERVICES ───────────────────────────────────────────────
  {
    id: "ps-send-proactive-updates",
    title: "Send proactive client updates",
    description: "Email clients on status changes so communication stays consistent without extra effort.",
    triggerIcon: Target,
    actionIcon: Mail,
    badge: "popular",
    sections: ["professionalServices", "statuses", "email"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "ps-staff-by-practice-area",
    title: "Staff work by practice area",
    description: "Assign tasks by service type to match each request with the right specialist.",
    triggerIcon: SquarePen,
    actionIcon: Users,
    sections: ["professionalServices", "assignees"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "ps-advance-after-qa",
    title: "Advance delivery after QA completion",
    description: "Move client work forward when checklists are complete to preserve quality gates.",
    triggerIcon: CheckCircle2,
    actionIcon: Target,
    sections: ["professionalServices", "statuses"],
    mode: "classic",
    triggerType: "CHECKLISTS_RESOLVED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "ps-start-repeatable-structure",
    title: "Start engagements with repeatable structure",
    description: "Apply service templates at creation to standardize onboarding and delivery workflows.",
    triggerIcon: CirclePlus,
    actionIcon: Layers,
    sections: ["professionalServices", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "APPLY_TEMPLATE",
  },
  {
    id: "ps-escalate-client-deadlines",
    title: "Escalate client deadlines in time",
    description: "Raise priority automatically as due dates arrive so teams focus on urgent commitments.",
    triggerIcon: Calendar,
    actionIcon: Flag,
    sections: ["professionalServices", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "UPDATE_PRIORITY",
  },

  // ─── PROJECT MANAGEMENT ──────────────────────────────────────────────────
  {
    id: "pm-launch-proven-templates",
    title: "Launch projects from proven templates",
    description: "Apply your best-practice template on creation to keep planning fast and delivery consistent.",
    triggerIcon: CirclePlus,
    actionIcon: Layers,
    badge: "popular",
    sections: ["projectManagement", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "APPLY_TEMPLATE",
  },
  {
    id: "pm-advance-milestones",
    title: "Advance milestones automatically",
    description: "Move work to the next phase when all subtasks are complete to keep delivery flowing.",
    triggerIcon: CheckCircle2,
    actionIcon: Target,
    sections: ["projectManagement", "statuses"],
    mode: "classic",
    triggerType: "SUBTASKS_RESOLVED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "pm-keep-timelines-moving",
    title: "Keep timelines moving",
    description: "Update task status when due dates arrive so at-risk work is surfaced without manual checks.",
    triggerIcon: Calendar,
    actionIcon: Target,
    sections: ["projectManagement", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "pm-capture-progress-context",
    title: "Capture progress context",
    description: "Add contextual comments on status updates so teams always understand momentum and blockers.",
    triggerIcon: Target,
    actionIcon: MessageSquare,
    sections: ["projectManagement", "statuses"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "pm-reassign-when-unblocked",
    title: "Reassign work when unblocked",
    description: "Hand work to the right owner as soon as blockers clear to reduce idle time.",
    triggerIcon: UserCheck,
    actionIcon: Users,
    sections: ["projectManagement", "assignees"],
    mode: "classic",
    triggerType: "TASK_UNBLOCKED",
    actionType: "UPDATE_ASSIGNEES",
  },

  // ─── ASSIGNEES ───────────────────────────────────────────────────────────
  {
    id: "asg-classify-by-owner",
    title: "Classify work by owner",
    description: "Set task type from assignee changes to keep work routing and reporting aligned.",
    triggerIcon: UserPlus,
    actionIcon: Box,
    sections: ["assignees", "taskTypes"],
    mode: "classic",
    triggerType: "TASK_ASSIGNEE_CHANGED",
    actionType: "UPDATE_TASK_TYPE",
  },
  {
    id: "asg-assign-by-location",
    title: "Assign by workflow location",
    description: "Reassign tasks as they move between lists so ownership matches each stage.",
    triggerIcon: ArrowRightToLine,
    actionIcon: UserPlus,
    sections: ["assignees", "move"],
    mode: "classic",
    triggerType: "MOVE_TO_LIST",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "asg-deadlines-on-owner-change",
    title: "Set deadlines when owners change",
    description: "Apply due-date logic on reassignment so handoffs keep momentum.",
    triggerIcon: UserPlus,
    actionIcon: Calendar,
    sections: ["assignees", "dates"],
    mode: "classic",
    triggerType: "TASK_ASSIGNEE_CHANGED",
    actionType: "UPDATE_DUE_DATE",
  },
  {
    id: "asg-escalate-ownership",
    title: "Escalate ownership automatically",
    description: "Move high-priority work to the right owner instantly when urgency increases.",
    triggerIcon: Flag,
    actionIcon: UserPlus,
    sections: ["assignees", "dates"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "UPDATE_ASSIGNEES",
  },

  // ─── CREATION ────────────────────────────────────────────────────────────
  {
    id: "cre-spin-up-followup",
    title: "Spin up follow-up tasks automatically",
    description: "Create the next task as ownership changes to keep workflows moving without gaps.",
    triggerIcon: UserPlus,
    actionIcon: CirclePlus,
    sections: ["creation", "assignees"],
    mode: "classic",
    triggerType: "TASK_ASSIGNEE_CHANGED",
    actionType: "CREATE_TASK",
  },
  {
    id: "cre-assign-new-instantly",
    title: "Assign new work instantly",
    description: "Route new tasks to the right owner at creation so response starts faster.",
    triggerIcon: CirclePlus,
    actionIcon: UserPlus,
    sections: ["creation", "assignees"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_ASSIGNEE",
    applyTemplateId: "auto-assign",
  },
  {
    id: "cre-deadline-followthrough",
    title: "Generate deadline follow-through",
    description: "Create follow-up tasks on due-date milestones to ensure commitments stay on track.",
    triggerIcon: Calendar,
    actionIcon: CirclePlus,
    sections: ["creation", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "CREATE_TASK",
  },

  // ─── DATES ───────────────────────────────────────────────────────────────
  {
    id: "dat-escalate-deadlines-shift",
    title: "Escalate work as deadlines shift",
    description: "Update priority when due dates change so urgent work gets immediate attention.",
    triggerIcon: Calendar,
    actionIcon: Flag,
    sections: ["dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_CHANGED",
    actionType: "UPDATE_PRIORITY",
  },
  {
    id: "dat-start-right-time",
    title: "Start work at the right time",
    description: "Set start dates from priority rules to coordinate effort and reduce bottlenecks.",
    triggerIcon: Flag,
    actionIcon: Calendar,
    sections: ["dates"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "UPDATE_START_DATE",
  },
  {
    id: "dat-activate-ownership",
    title: "Activate ownership on due dates",
    description: "Assign responsible owners when due dates arrive so nothing slips through the cracks.",
    triggerIcon: Calendar,
    actionIcon: UserPlus,
    sections: ["dates", "assignees"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "dat-set-deadlines-urgency",
    title: "Set deadlines by urgency",
    description: "Adjust due dates from priority updates to keep delivery plans realistic and responsive.",
    triggerIcon: Flag,
    actionIcon: Calendar,
    sections: ["dates"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "UPDATE_DUE_DATE",
  },

  // ─── MOVE ────────────────────────────────────────────────────────────────
  {
    id: "mov-progress-lists-change",
    title: "Progress work when lists change",
    description: "Update status automatically when tasks move across lists so every handoff stays clear.",
    triggerIcon: ArrowRightToLine,
    actionIcon: Target,
    sections: ["move", "statuses"],
    mode: "classic",
    triggerType: "MOVE_TO_LIST",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "mov-route-right-list",
    title: "Route tasks to the right list",
    description: "Move tasks into the best-fit list as statuses change to keep workflows organized.",
    triggerIcon: Target,
    actionIcon: ArrowRightToLine,
    sections: ["move", "statuses"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "MOVE_TO_LIST",
  },
  {
    id: "mov-handoff-stage",
    title: "Hand off ownership by workflow stage",
    description: "Assign the right owner when tasks enter a new list so responsibility is always obvious.",
    triggerIcon: ArrowRightToLine,
    actionIcon: UserPlus,
    sections: ["move", "assignees"],
    mode: "classic",
    triggerType: "MOVE_TO_LIST",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "mov-sort-custom-criteria",
    title: "Sort work by custom criteria",
    description: "Use custom field changes to auto-place tasks into the most relevant list.",
    triggerIcon: SquarePen,
    actionIcon: ArrowRightToLine,
    sections: ["move"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "MOVE_TO_LIST",
  },

  // ─── STATUSES ────────────────────────────────────────────────────────────
  {
    id: "sta-assign-next-owner",
    title: "Assign the next owner instantly",
    description: "Update assignees as status changes so work keeps moving without manual triage.",
    triggerIcon: Target,
    actionIcon: UserPlus,
    sections: ["statuses", "assignees"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "sta-reflect-due-date",
    title: "Reflect due-date reality",
    description: "Shift status when due dates arrive so teams see risk and urgency at a glance.",
    triggerIcon: Calendar,
    actionIcon: Target,
    sections: ["statuses", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "sta-escalate-stage",
    title: "Escalate focus by stage",
    description: "Adjust priority from status transitions to spotlight the most important work automatically.",
    triggerIcon: Target,
    actionIcon: Flag,
    sections: ["statuses"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "UPDATE_PRIORITY",
  },
  {
    id: "sta-drive-from-signals",
    title: "Drive status from key signals",
    description: "Set status from custom field updates so execution always reflects current context.",
    triggerIcon: SquarePen,
    actionIcon: Target,
    sections: ["statuses"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_STATUS",
  },

  // ─── TASK TYPES ──────────────────────────────────────────────────────────
  {
    id: "typ-autoprioritize-type",
    title: "Auto-prioritize by task type",
    description: "Map item types to priority rules so high-impact work rises to the top automatically.",
    triggerIcon: Box,
    actionIcon: Flag,
    sections: ["taskTypes"],
    mode: "classic",
    triggerType: "TASK_TYPE_CHANGED",
    actionType: "UPDATE_PRIORITY",
  },
  {
    id: "typ-classify-confidence",
    title: "Classify work with confidence",
    description: "Set task type from custom field data to keep your taxonomy clean and consistent.",
    triggerIcon: SquarePen,
    actionIcon: Box,
    sections: ["taskTypes"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_TASK_TYPE",
  },
  {
    id: "typ-smart-deadlines",
    title: "Set smart deadlines by type",
    description: "Apply due-date logic per task type so timelines stay realistic and predictable.",
    triggerIcon: Box,
    actionIcon: Calendar,
    sections: ["taskTypes", "dates"],
    mode: "classic",
    triggerType: "TASK_TYPE_CHANGED",
    actionType: "UPDATE_DUE_DATE",
  },
  {
    id: "typ-align-urgency",
    title: "Align type with business urgency",
    description: "Update task type from priority changes so categorization matches business impact.",
    triggerIcon: Flag,
    actionIcon: Box,
    sections: ["taskTypes"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "UPDATE_TASK_TYPE",
  },

  // ─── WEBHOOKS ────────────────────────────────────────────────────────────
  {
    id: "wh-notify-creation",
    title: "Notify external systems on task creation",
    description: "Send a webhook whenever a task is created so downstream tools stay in sync.",
    triggerIcon: CirclePlus,
    actionIcon: Webhook,
    badge: "popular",
    sections: ["webhook", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "wh-sync-systems-realtime",
    title: "Sync systems in real time",
    description: "Trigger webhooks from custom field updates to keep downstream tools aligned automatically.",
    triggerIcon: SquarePen,
    actionIcon: Webhook,
    badge: "popular",
    sections: ["webhook"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "CALL_WEBHOOK",
  },

  // ─── BUGSNAG ─────────────────────────────────────────────────────────────
  {
    id: "bug-route-reopened",
    title: "Route reopened errors instantly",
    description: "Reassign reopened Bugsnag errors to the right owner so remediation starts without delay.",
    triggerIcon: Bug,
    actionIcon: UserPlus,
    sections: ["bugsnag"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "bug-sync-status-error",
    title: "Sync task status to error state",
    description: "Keep Bugsnag error status aligned with task progress so triage stays accurate.",
    triggerIcon: Bug,
    actionIcon: Target,
    sections: ["bugsnag"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "bug-fix-deadlines-release",
    title: "Set fix deadlines by release",
    description: "Apply due dates when releases move so teams have clear targets for bug resolution.",
    triggerIcon: Flag,
    actionIcon: Calendar,
    sections: ["bugsnag"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "UPDATE_DUE_DATE",
  },
  {
    id: "bug-escalate-priority",
    title: "Escalate errors with task priority",
    description: "Update Bugsnag error status from task priority changes to surface high-impact issues faster.",
    triggerIcon: Flag,
    actionIcon: Bug,
    sections: ["bugsnag"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "bug-capture-context",
    title: "Capture exception context automatically",
    description: "Post exception details as comments so responders have immediate troubleshooting context.",
    triggerIcon: Bug,
    actionIcon: MessageSquare,
    sections: ["bugsnag"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "bug-flag-overdue",
    title: "Flag overdue fixes in Bugsnag",
    description: "Change error status when due dates pass so overdue issues are visible right away.",
    triggerIcon: Calendar,
    actionIcon: Bug,
    sections: ["bugsnag"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "UPDATE_STATUS",
  },

  // ─── CALENDLY ────────────────────────────────────────────────────────────
  {
    id: "cal-assign-followups",
    title: "Assign follow-ups from meetings",
    description: "Automatically route meeting tasks to the right owner as events are created.",
    triggerIcon: CalendarCheck,
    actionIcon: UserPlus,
    sections: ["calendly"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "UPDATE_ASSIGNEES",
  },
  {
    id: "cal-prioritize-meetings",
    title: "Prioritize work from new meetings",
    description: "Set priority from Calendly event details so urgent meetings get immediate attention.",
    triggerIcon: CalendarCheck,
    actionIcon: Flag,
    sections: ["calendly"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "UPDATE_PRIORITY",
  },
  {
    id: "cal-advance-status",
    title: "Advance status when meetings book",
    description: "Move tasks into the right stage as soon as events are scheduled.",
    triggerIcon: CalendarCheck,
    actionIcon: Target,
    sections: ["calendly"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "cal-due-dates-timing",
    title: "Set due dates from event timing",
    description: "Use booked meeting times to auto-apply clear due dates for next steps.",
    triggerIcon: CalendarCheck,
    actionIcon: Calendar,
    sections: ["calendly"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "UPDATE_DUE_DATE",
  },
  {
    id: "cal-log-meeting-details",
    title: "Log meeting details instantly",
    description: "Post event summaries as comments so everyone sees what was booked and why.",
    triggerIcon: CalendarCheck,
    actionIcon: MessageSquare,
    sections: ["calendly"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },

  // ─── EMAIL ───────────────────────────────────────────────────────────────
  {
    id: "eml-send-kickoff",
    title: "Send polished kickoff emails",
    description: "Automatically send clear kickoff emails when tasks are created to align stakeholders from day one.",
    triggerIcon: CirclePlus,
    actionIcon: Mail,
    sections: ["email", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "eml-notify-assignment-changes",
    title: "Notify owners on assignment changes",
    description: "Email the right people when ownership shifts so handoffs never get missed.",
    triggerIcon: UserPlus,
    actionIcon: Mail,
    sections: ["email", "assignees"],
    mode: "classic",
    triggerType: "TASK_ASSIGNEE_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "eml-alert-priority-shifts",
    title: "Alert teams to priority shifts",
    description: "Send instant updates on priority changes so teams can react to critical work quickly.",
    triggerIcon: Flag,
    actionIcon: Mail,
    sections: ["email"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "eml-trigger-key-tags",
    title: "Trigger updates from key tags",
    description: "Email stakeholders when strategic tags are added to keep campaigns and initiatives coordinated.",
    triggerIcon: Flag,
    actionIcon: Mail,
    sections: ["email"],
    mode: "classic",
    triggerType: "TAG_ADDED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "eml-deadlines-inbox",
    title: "Keep deadlines top of inbox",
    description: "Automatically send deadline-change emails so schedules stay visible and actionable.",
    triggerIcon: Calendar,
    actionIcon: Mail,
    sections: ["email", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "eml-day-of-reminders",
    title: "Send day-of deadline reminders",
    description: "Deliver due-date reminders right on time so no commitment slips through.",
    triggerIcon: Calendar,
    actionIcon: Mail,
    sections: ["email", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "ADD_COMMENT",
  },

  // ─── GITHUB ──────────────────────────────────────────────────────────────
  {
    id: "gh-advance-pr-merge",
    title: "Advance tasks when PRs merge",
    description: "Move work forward automatically when pull requests merge so delivery status stays trustworthy.",
    triggerIcon: GitPullRequest,
    actionIcon: Target,
    sections: ["github", "development"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_UPDATED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "gh-open-issues-priority",
    title: "Open issues for high-priority work",
    description: "Create GitHub issues from urgent priorities so engineering can execute without delay.",
    triggerIcon: Flag,
    actionIcon: GitBranch,
    sections: ["github", "development"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "gh-surface-review-blockers",
    title: "Surface code review blockers fast",
    description: "Post review-change requests as comments so teams can clear blockers immediately.",
    triggerIcon: GitPullRequest,
    actionIcon: MessageSquare,
    sections: ["github", "development"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_UPDATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "gh-create-issues-deadlines",
    title: "Create issues from looming deadlines",
    description: "Spin up GitHub issues as due dates approach to keep delivery commitments on track.",
    triggerIcon: Calendar,
    actionIcon: GitBranch,
    sections: ["github", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "gh-generate-from-tags",
    title: "Generate issues from release tags",
    description: "Turn key tags into GitHub issues to standardize release and follow-up workflows.",
    triggerIcon: Flag,
    actionIcon: GitBranch,
    sections: ["github"],
    mode: "classic",
    triggerType: "TAG_ADDED",
    actionType: "CALL_WEBHOOK",
  },

  // ─── GOOGLE CALENDAR ─────────────────────────────────────────────────────
  {
    id: "gcal-create-tasks-updates",
    title: "Create tasks from calendar updates",
    description: "Turn new or updated calendar events into tasks so execution starts instantly.",
    triggerIcon: CalendarCheck,
    actionIcon: CirclePlus,
    sections: ["google-calendar"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "CREATE_TASK",
  },
  {
    id: "gcal-open-followups-cancelled",
    title: "Open follow-ups when events cancel",
    description: "Create cleanup tasks on canceled events so plans are rescheduled without confusion.",
    triggerIcon: CalendarX,
    actionIcon: CirclePlus,
    sections: ["google-calendar"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_UPDATED",
    actionType: "CREATE_TASK",
  },
  {
    id: "gcal-schedule-new-tasks",
    title: "Schedule events from new tasks",
    description: "Create Google Calendar events automatically from tasks to lock in time immediately.",
    triggerIcon: CirclePlus,
    actionIcon: CalendarPlus,
    sections: ["google-calendar"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "gcal-book-right-stage",
    title: "Book events at the right stage",
    description: "Trigger calendar event creation from status changes so coordination happens at the perfect moment.",
    triggerIcon: Target,
    actionIcon: CalendarPlus,
    sections: ["google-calendar"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "gcal-clear-deprioritized",
    title: "Clear events for deprioritized work",
    description: "Delete stale calendar events when priorities drop so schedules stay focused.",
    triggerIcon: Flag,
    actionIcon: CalendarX,
    sections: ["google-calendar"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "gcal-keep-timing-synced",
    title: "Keep event timing synced",
    description: "Update event details from due-date changes so calendars always reflect the latest plan.",
    triggerIcon: Calendar,
    actionIcon: CalendarClock,
    sections: ["google-calendar", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_CHANGED",
    actionType: "ADD_COMMENT",
  },

  // ─── GOOGLE DRIVE ────────────────────────────────────────────────────────
  {
    id: "gdrv-folders-new-tasks",
    title: "Create Drive folders for new tasks",
    description: "Automatically spin up Google Drive folders so every project has organized storage from kickoff.",
    triggerIcon: CirclePlus,
    actionIcon: FolderPlus,
    badge: "new",
    sections: ["google-drive", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "gdrv-generate-docs-kickoff",
    title: "Generate docs at kickoff",
    description: "Create Google Docs from new tasks so teams can start collaborating instantly.",
    triggerIcon: CirclePlus,
    actionIcon: FileText,
    badge: "new",
    sections: ["google-drive", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "gdrv-announce-files-chat",
    title: "Announce new Drive files in chat",
    description: "Post messages when files are created to keep teams informed without manual updates.",
    triggerIcon: FileText,
    actionIcon: MessageSquare,
    badge: "new",
    sections: ["google-drive"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_UPDATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "gdrv-dm-owners-files",
    title: "DM owners when files appear",
    description: "Send direct notifications for new files so key stakeholders can review immediately.",
    triggerIcon: FileText,
    actionIcon: Send,
    badge: "new",
    sections: ["google-drive"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_UPDATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "gdrv-share-folder-updates",
    title: "Share folder creation updates",
    description: "Broadcast newly created folders so teams can access assets faster.",
    triggerIcon: FolderPlus,
    actionIcon: MessageSquare,
    badge: "new",
    sections: ["google-drive"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "gdrv-send-links-directly",
    title: "Send folder links directly",
    description: "Direct-message folder creation events to owners so onboarding starts instantly.",
    triggerIcon: FolderPlus,
    actionIcon: Send,
    badge: "new",
    sections: ["google-drive"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },

  // ─── HUBSPOT ─────────────────────────────────────────────────────────────
  {
    id: "hub-log-contact-activity",
    title: "Log new contact activity automatically",
    description: "Post HubSpot contact creation updates to tasks so customer context is captured instantly.",
    triggerIcon: UserPlus,
    actionIcon: MessageSquare,
    sections: ["hubspot"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "hub-align-deal-urgency",
    title: "Align deal urgency with task priority",
    description: "Update HubSpot deals when task priority changes so revenue work is triaged correctly.",
    triggerIcon: Flag,
    actionIcon: Target,
    sections: ["hubspot"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "hub-update-products-tags",
    title: "Update products from strategic tags",
    description: "Use task tags to sync HubSpot product data and keep GTM systems aligned.",
    triggerIcon: Flag,
    actionIcon: RefreshCw,
    sections: ["hubspot"],
    mode: "classic",
    triggerType: "TAG_ADDED",
    actionType: "CALL_WEBHOOK",
  },
  {
    id: "hub-move-statuses-deals",
    title: "Move statuses with deal changes",
    description: "Advance task status based on HubSpot deal updates so teams always work the latest pipeline state.",
    triggerIcon: Target,
    actionIcon: Target,
    sections: ["hubspot", "statuses"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "UPDATE_STATUS",
  },
  {
    id: "hub-create-deals-signals",
    title: "Create deals from key field signals",
    description: "Generate HubSpot deals from custom field changes to accelerate qualified opportunity handoff.",
    triggerIcon: SquarePen,
    actionIcon: CirclePlus,
    sections: ["hubspot"],
    mode: "classic",
    triggerType: "CUSTOM_FIELD_CHANGED",
    actionType: "CALL_WEBHOOK",
  },

  // ─── SLACK ───────────────────────────────────────────────────────────────
  {
    id: "slk-broadcast-status-slack",
    title: "Broadcast status changes to Slack",
    description: "Post channel updates automatically on status changes so teams stay aligned in real time.",
    triggerIcon: Target,
    actionIcon: MessageSquare,
    badge: "new",
    sections: ["slack", "statuses"],
    mode: "classic",
    triggerType: "TASK_STATUS_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "slk-slack-messages-to-tasks",
    title: "Turn Slack messages into tasks",
    description: "Convert channel requests into trackable tasks so action items never get lost.",
    triggerIcon: MessageSquare,
    actionIcon: CirclePlus,
    badge: "new",
    sections: ["slack", "creation"],
    mode: "classic",
    triggerType: "CHAT_MESSAGE_POSTED",
    actionType: "CREATE_TASK",
  },
  {
    id: "slk-announce-ownership-channel",
    title: "Announce ownership changes in channel",
    description: "Notify Slack channels when assignees change so everyone knows who is driving next steps.",
    triggerIcon: UserPlus,
    actionIcon: MessageSquare,
    badge: "new",
    sections: ["slack", "assignees"],
    mode: "classic",
    triggerType: "TASK_ASSIGNEE_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "slk-channel-followups",
    title: "Send channel follow-ups from Slack activity",
    description: "Trigger ClickUp chat updates from posted Slack messages to keep execution context connected.",
    triggerIcon: MessageSquare,
    actionIcon: MessageSquare,
    badge: "new",
    sections: ["slack"],
    mode: "classic",
    triggerType: "CHAT_MESSAGE_POSTED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "slk-dm-responders",
    title: "Direct-message key responders instantly",
    description: "Send immediate DMs from Slack channel events so owners can respond faster.",
    triggerIcon: MessageSquare,
    actionIcon: Send,
    badge: "new",
    sections: ["slack"],
    mode: "classic",
    triggerType: "CHAT_MESSAGE_POSTED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "slk-deadline-alerts-slack",
    title: "Post deadline alerts to Slack",
    description: "Push due-date reminders to channels so time-sensitive work stays visible.",
    triggerIcon: Calendar,
    actionIcon: MessageSquare,
    badge: "new",
    sections: ["slack", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "ADD_COMMENT",
  },

  // ─── TWILIO ──────────────────────────────────────────────────────────────
  {
    id: "twi-instant-kickoff-texts",
    title: "Send instant kickoff texts",
    description: "Text critical updates when tasks are created so execution begins immediately.",
    triggerIcon: CirclePlus,
    actionIcon: PhoneCall,
    sections: ["twilio", "creation"],
    mode: "classic",
    triggerType: "TASK_OR_SUBTASK_CREATED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "twi-text-owners-assignment",
    title: "Text owners on assignment changes",
    description: "Notify assignees by SMS when ownership changes so handoffs are impossible to miss.",
    triggerIcon: UserPlus,
    actionIcon: PhoneCall,
    sections: ["twilio", "assignees"],
    mode: "classic",
    triggerType: "TASK_ASSIGNEE_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "twi-alert-priority-changes",
    title: "Alert teams to priority changes",
    description: "Trigger SMS alerts on priority updates to speed responses for urgent work.",
    triggerIcon: Flag,
    actionIcon: PhoneCall,
    sections: ["twilio"],
    mode: "classic",
    triggerType: "TASK_PRIORITY_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "twi-text-key-tags",
    title: "Text updates from key tags",
    description: "Send SMS notifications from strategic tags to keep programs synchronized across teams.",
    triggerIcon: Flag,
    actionIcon: PhoneCall,
    sections: ["twilio"],
    mode: "classic",
    triggerType: "TAG_ADDED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "twi-deadlines-text",
    title: "Keep deadlines visible by text",
    description: "Send due-date SMS reminders so high-stakes deadlines stay front and center.",
    triggerIcon: Calendar,
    actionIcon: PhoneCall,
    sections: ["twilio", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_CHANGED",
    actionType: "ADD_COMMENT",
  },
  {
    id: "twi-day-of-texts",
    title: "Send day-of due date texts",
    description: "Deliver same-day SMS reminders to prevent deadline slips.",
    triggerIcon: Calendar,
    actionIcon: PhoneCall,
    sections: ["twilio", "dates"],
    mode: "classic",
    triggerType: "TASK_DUE_DATE_ARRIVES",
    actionType: "ADD_COMMENT",
  },
];

export const BROWSE_NAV = [
  {
    heading: "Featured",
    items: [{ id: "popular" as BrowseSectionId, label: "Popular", icon: Flame }],
  },
  {
    heading: "Solutions",
    items: [
      { id: "development" as BrowseSectionId, label: "Development", icon: Settings2 },
      { id: "marketing" as BrowseSectionId, label: "Marketing", icon: Settings2 },
      { id: "professionalServices" as BrowseSectionId, label: "Professional Services", icon: Settings2 },
      { id: "projectManagement" as BrowseSectionId, label: "Project Management", icon: Settings2 },
    ],
  },
  {
    heading: "Categories",
    items: [
      { id: "assignees" as BrowseSectionId, label: "Assignees", icon: UserPlus },
      { id: "creation" as BrowseSectionId, label: "Creation", icon: CirclePlus },
      { id: "dates" as BrowseSectionId, label: "Dates", icon: Calendar },
      { id: "move" as BrowseSectionId, label: "Move", icon: ArrowRightToLine },
      { id: "statuses" as BrowseSectionId, label: "Statuses", icon: Target },
      { id: "taskTypes" as BrowseSectionId, label: "Task Types", icon: Box },
      { id: "webhook" as BrowseSectionId, label: "Webhook", icon: Webhook },
    ],
  },
] as const;

export const BROWSE_INTEGRATIONS = [
  { id: "bugsnag" as BrowseSectionId, label: "Bugsnag" },
  { id: "calendly" as BrowseSectionId, label: "Calendly" },
  { id: "email" as BrowseSectionId, label: "Email" },
  { id: "github" as BrowseSectionId, label: "GitHub" },
  { id: "google-calendar" as BrowseSectionId, label: "Google Calendar" },
  { id: "google-drive" as BrowseSectionId, label: "Google Drive", isNew: true },
  { id: "hubspot" as BrowseSectionId, label: "HubSpot" },
  { id: "slack" as BrowseSectionId, label: "Slack", isNew: true },
  { id: "twilio" as BrowseSectionId, label: "Twilio" },
] as const;

export const ALL_BROWSE_SECTIONS: BrowseSectionId[] = [
  "popular",
  "development",
  "marketing",
  "professionalServices",
  "projectManagement",
  "assignees",
  "creation",
  "dates",
  "move",
  "statuses",
  "taskTypes",
  "webhook",
  "bugsnag",
  "calendly",
  "email",
  "github",
  "google-calendar",
  "google-drive",
  "hubspot",
  "slack",
  "twilio",
];

export const SECTION_TITLES: Record<BrowseSectionId, string> = {
  popular: "Popular",
  development: "Development",
  marketing: "Marketing",
  professionalServices: "Professional Services",
  projectManagement: "Project Management",
  assignees: "Assignees",
  creation: "Creation",
  dates: "Dates",
  move: "Move",
  statuses: "Statuses",
  taskTypes: "Task Types",
  webhook: "Webhooks",
  bugsnag: "Bugsnag",
  calendly: "Calendly",
  email: "Email",
  github: "GitHub",
  "google-calendar": "Google Calendar",
  "google-drive": "Google Drive",
  hubspot: "HubSpot",
  slack: "Slack",
  twilio: "Twilio",
};
